apiVersion: core.kubestash.com/v1alpha1
kind: BackupConfiguration
metadata:
  name: es-db-backup
  namespace: demo
spec:
  target:
    apiGroup: kubedb.com
    kind: Elasticsearch
    namespace: demo
    name: sample-es
  backends:
  - name: gcs-storage
    storageRef:
      name: gcs-storage
      namespace: demo
    retentionPolicy:
      name: demo-retention
      namespace: demo
  sessions:
  - name: frequent-backup
    scheduler:
      schedule: "*/3 * * * *"
    repositories:
    - name: gcs-repo-es
      backend: gcs-storage
      directory: /sample/kubestashs/elastic
      encryptionSecret:
        name: encrypt-secret # some addon may not support encryption
        namespace: demo
    addon:
      name: elasticsearch-addon
      tasks:
      - name: logical-backup
        addonVolumes:
        - name: ${INTERIM_VOLUME}
          source:
            volumeClaimTemplate:
              spec:
                accessModes:
                - ReadWriteOnce
                resources:
                  requests:
                    storage: 1Gi
        - name: kubestash-tmp-volume
          source:
            persistentVolumeClaim:
              claimName: backup-target-pvc

            # volumeClaimTemplate:
            #   spec:
            #     accessModes:
            #     - ReadWriteOnce
            #     resources:
            #       requests:
            #         storage: 1Gi
      jobTemplate:
        spec:
          securityContext:
            runAsUser: 0
            runAsGroup: 0