apiVersion: addons.kubestash.com/v1alpha1
kind: Addon
metadata:
  annotations:
    meta.helm.sh/release-name: kubedb
    meta.helm.sh/release-namespace: kubedb
  creationTimestamp: "2025-04-28T11:28:31Z"
  generation: 1
  labels:
    app.kubernetes.io/instance: kubedb
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: kubedb-kubestash-catalog
    app.kubernetes.io/version: v2025.3.24
    helm.sh/chart: kubedb-kubestash-catalog-v2025.3.24
  managedFields:
  - apiVersion: addons.kubestash.com/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:meta.helm.sh/release-name: {}
          f:meta.helm.sh/release-namespace: {}
        f:labels:
          .: {}
          f:app.kubernetes.io/instance: {}
          f:app.kubernetes.io/managed-by: {}
          f:app.kubernetes.io/name: {}
          f:app.kubernetes.io/version: {}
          f:helm.sh/chart: {}
      f:spec:
        .: {}
        f:backupTasks: {}
        f:restoreTasks: {}
    manager: helm
    operation: Update
    time: "2025-04-28T11:28:31Z"
  name: redis-addon
  resourceVersion: "59217"
  uid: b9231f19-088d-4695-868b-2d10f79045d1
spec:
  backupTasks:
  - driver: Restic
    executor: Job
    function: redis-backup
    name: logical-backup
    parameters:
    - name: args
      required: false
      usage: Arguments to be passed to the dump command.
    - default: "true"
      name: enableCache
      required: false
      usage: Enable or disable caching. Disabling caching may impact backup performance.
    - default: /kubestash-tmp
      name: scratchDir
      required: false
      usage: Directory for holding temporary files and restic cache.
    singleton: true
    volumeMounts:
    - mountPath: /kubestash-tmp
      name: kubestash-tmp-volume
    volumeTemplate:
    - name: kubestash-tmp-volume
      source:
        emptyDir: {}
      usage: Holds temporary files and restic cache.
  restoreTasks:
  - driver: Restic
    executor: Job
    function: redis-restore
    name: logical-backup-restore
    parameters:
    - name: args
      required: false
      usage: Arguments to be passed to the dump command.
    - default: "true"
      name: enableCache
      required: false
      usage: Enable or disable caching. Disabling caching may impact backup performance.
    - default: /kubestash-tmp
      name: scratchDir
      required: false
      usage: Directory for holding temporary files and restic cache.
    singleton: true
    volumeMounts:
    - mountPath: /kubestash-tmp
      name: kubestash-tmp-volume
    volumeTemplate:
    - name: kubestash-tmp-volume
      source:
        emptyDir: {}
      usage: Holds temporary files and restic cache.
