apiVersion: metrics.appscode.com/v1alpha1
kind: MetricsConfiguration
metadata:
  annotations:
    meta.helm.sh/release-name: kubestash
    meta.helm.sh/release-namespace: kubestash
  creationTimestamp: "2025-04-25T10:31:48Z"
  generation: 1
  labels:
    app.kubernetes.io/managed-by: Helm
  managedFields:
  - apiVersion: metrics.appscode.com/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:meta.helm.sh/release-name: {}
          f:meta.helm.sh/release-namespace: {}
        f:labels:
          .: {}
          f:app.kubernetes.io/managed-by: {}
      f:spec:
        .: {}
        f:commonLabels: {}
        f:metrics: {}
        f:targetRef:
          .: {}
          f:apiVersion: {}
          f:kind: {}
    manager: helm
    operation: Update
    time: "2025-04-25T10:31:48Z"
  name: kubestash-appscode-com-backupsession
  resourceVersion: "1722"
  uid: e6e324b4-a2c1-4de6-9c53-c415a13813d9
spec:
  commonLabels:
  - key: invoker_kind
    value: BackupSession
  - key: invoker_name
    valuePath: .metadata.name
  - key: backup_invoker_kind
    valuePath: .spec.invoker.kind
  - key: backup_invoker_name
    valuePath: .spec.invoker.name
  metrics:
  - field:
      path: .metadata.creationTimestamp
      type: DateTime
    help: Unix creation timestamp of this BackupSession object
    metricValue:
      valueFromPath: .metadata.creationTimestamp
    name: created
    type: gauge
  - help: General information about this BackupSession
    labels:
    - key: session
      valuePath: .spec.session
    - key: phase
      valuePath: .status.phase
    metricValue:
      value: 1
    name: info
    type: gauge
  - field:
      path: .status.snapshots
      type: Array
    help: General information about the snapshots of this BackupSession
    labels:
    - key: snapshot_name
      valuePath: .status.snapshots[*].name
    - key: snapshot_phase
      valuePath: .status.snapshots[*].phase
    - key: repository
      valuePath: .status.snapshots[*].repository
    - key: backedup_app_kind
      valuePath: .status.snapshots[*].appRef.kind
    - key: backedup_app_name
      valuePath: .status.snapshots[*].appRef.name
    - key: backedup_app_namespace
      valuePath: .status.snapshots[*].appRef.namespace
    metricValue:
      value: 1
    name: snapshots
    type: gauge
  - field:
      path: .status.phase
      type: String
    help: BackupSession object current phase
    name: phase
    params:
    - key: phase
      valuePath: .status.phase
    states:
      labelKey: phase
      values:
      - labelValue: Pending
        metricValue:
          valueFromExpression: int(phase == 'Pending')
      - labelValue: Running
        metricValue:
          valueFromExpression: int(phase == 'Running')
      - labelValue: Succeeded
        metricValue:
          valueFromExpression: int(phase == 'Succeeded')
      - labelValue: Failed
        metricValue:
          valueFromExpression: int(phase == 'Failed')
      - labelValue: Skipped
        metricValue:
          valueFromExpression: int(phase == 'Skipped')
    type: gauge
  - field:
      path: .status.duration
      type: String
    help: Time required to complete this backup process
    metricValue:
      valueFromExpression: toSecond(duration)
    name: duration_seconds
    params:
    - key: duration
      valuePath: .status.duration
    type: gauge
  - field:
      path: .status.conditions
      type: Array
    help: Current conditions of this BackupSession
    labels:
    - key: condition
      valuePath: .status.conditions[*].type
    - key: status
      valuePath: .status.conditions[*].status
    metricValue:
      value: 1
    name: conditions
    type: gauge
  targetRef:
    apiVersion: core.kubestash.com/v1alpha1
    kind: BackupSession
