apiVersion: metrics.appscode.com/v1alpha1
kind: MetricsConfiguration
metadata:
  annotations:
    meta.helm.sh/release-name: kubestash
    meta.helm.sh/release-namespace: kubestash
  creationTimestamp: "2025-04-25T10:31:48Z"
  generation: 1
  labels:
    app.kubernetes.io/managed-by: Helm
  managedFields:
  - apiVersion: metrics.appscode.com/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:meta.helm.sh/release-name: {}
          f:meta.helm.sh/release-namespace: {}
        f:labels:
          .: {}
          f:app.kubernetes.io/managed-by: {}
      f:spec:
        .: {}
        f:commonLabels: {}
        f:metrics: {}
        f:targetRef:
          .: {}
          f:apiVersion: {}
          f:kind: {}
    manager: helm
    operation: Update
    time: "2025-04-25T10:31:48Z"
  name: kubestash-appscode-com-backupconfiguration
  resourceVersion: "1719"
  uid: 2c6202ac-7586-401d-9c62-1e7fa04360b4
spec:
  commonLabels:
  - key: backup_invoker_kind
    value: BackupConfiguration
  - key: backup_invoker_name
    valuePath: .metadata.name
  - key: target_kind
    valuePath: .spec.target.kind
  - key: target_name
    valuePath: .spec.target.name
  - key: target_namespace
    valuePath: .spec.target.namespace
  metrics:
  - field:
      path: .metadata.creationTimestamp
      type: DateTime
    help: Unix creation timestamp of this BackupConfiguration object
    metricValue:
      valueFromPath: .metadata.creationTimestamp
    name: created
    type: gauge
  - help: General information about this BackupConfiguration
    metricValue:
      value: 1
    name: info
    type: gauge
  - field:
      path: .spec.sessions
      type: Array
    help: List of sessions of this BackupConfiguration
    labels:
    - key: session_name
      valuePath: .spec.sessions[*].name
    - key: schedule
      valuePath: .spec.sessions[*].scheduler.schedule
    - key: addon_name
      valuePath: .spec.sessions[*].addon.name
    metricValue:
      value: 1
    name: sessions
    type: gauge
  - field:
      path: .status.phase
      type: String
    help: BackupConfiguration object current phase
    name: phase
    params:
    - key: phase
      valuePath: .status.phase
    states:
      labelKey: phase
      values:
      - labelValue: Ready
        metricValue:
          valueFromExpression: int(phase == 'Ready')
      - labelValue: NotReady
        metricValue:
          valueFromExpression: int(phase == 'NotReady')
      - labelValue: Invalid
        metricValue:
          valueFromExpression: int(phase == 'Invalid')
    type: gauge
  - field:
      path: .status.conditions
      type: Array
    help: Current conditions of this BackupConfiguration
    labels:
    - key: condition
      valuePath: .status.conditions[*].type
    - key: status
      valuePath: .status.conditions[*].status
    metricValue:
      value: 1
    name: conditions
    type: gauge
  targetRef:
    apiVersion: core.kubestash.com/v1alpha1
    kind: BackupConfiguration
