apiVersion: metrics.appscode.com/v1alpha1
kind: MetricsConfiguration
metadata:
  annotations:
    meta.helm.sh/release-name: kubestash
    meta.helm.sh/release-namespace: kubestash
  creationTimestamp: "2025-04-25T10:31:48Z"
  generation: 1
  labels:
    app.kubernetes.io/managed-by: Helm
  managedFields:
  - apiVersion: metrics.appscode.com/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:meta.helm.sh/release-name: {}
          f:meta.helm.sh/release-namespace: {}
        f:labels:
          .: {}
          f:app.kubernetes.io/managed-by: {}
      f:spec:
        .: {}
        f:commonLabels: {}
        f:metrics: {}
        f:targetRef:
          .: {}
          f:apiVersion: {}
          f:kind: {}
    manager: helm
    operation: Update
    time: "2025-04-25T10:31:48Z"
  name: kubestash-appscode-com-snapshot
  resourceVersion: "1718"
  uid: 80946a92-01dd-42e9-a68d-4bd7b1ce8b9b
spec:
  commonLabels:
  - key: invoker_kind
    value: Snapshot
  - key: invoker_name
    valuePath: .metadata.name
  - key: target_kind
    valuePath: .spec.appRef.kind
  - key: target_name
    valuePath: .spec.appRef.name
  - key: target_namespace
    valuePath: .spec.appRef.namespace
  metrics:
  - field:
      path: .metadata.creationTimestamp
      type: DateTime
    help: Unix creation timestamp of this Snapshot object
    metricValue:
      valueFromPath: .metadata.creationTimestamp
    name: created
    type: gauge
  - help: General information about this Snapshot
    labels:
    - key: snapshot_type
      valuePath: .spec.type
    - key: repository
      valuePath: .spec.repository
    - key: session
      valuePath: .spec.session
    - key: backupsession
      valuePath: .spec.backupSession
    - key: version
      valuePath: .spec.version
    - key: phase
      valuePath: .status.phase
    - key: integrity
      valuePath: .status.integrity
    metricValue:
      value: 1
    name: info
    type: gauge
  - field:
      path: .status.phase
      type: String
    help: Snapshot object current phase
    name: phase
    params:
    - key: phase
      valuePath: .status.phase
    states:
      labelKey: phase
      values:
      - labelValue: Pending
        metricValue:
          valueFromExpression: int(phase == 'Pending')
      - labelValue: Running
        metricValue:
          valueFromExpression: int(phase == 'Running')
      - labelValue: Succeeded
        metricValue:
          valueFromExpression: int(phase == 'Succeeded')
      - labelValue: Failed
        metricValue:
          valueFromExpression: int(phase == 'Failed')
    type: gauge
  - field:
      path: .status.size
      type: String
    help: Size of this Snapshot
    metricValue:
      valueFromExpression: bytes(size)
    name: size_bytes
    params:
    - key: size
      valuePath: .status.size
    type: gauge
  - field:
      path: .status.snapshotTime
      type: DateTime
    help: The time when this Snapshot was taken
    metricValue:
      valueFromPath: .status.snapshotTime
    name: time_seconds
    type: gauge
  - field:
      path: .status.totalComponents
      type: Integer
    help: The number of total components for this Snapshot
    metricValue:
      valueFromPath: .status.totalComponents
    name: component_count_total
    type: gauge
  - field:
      path: .status.conditions
      type: Array
    help: Current conditions of this Snapshot
    labels:
    - key: condition
      valuePath: .status.conditions[*].type
    - key: status
      valuePath: .status.conditions[*].status
    metricValue:
      value: 1
    name: conditions
    type: gauge
  targetRef:
    apiVersion: storage.kubestash.com/v1alpha1
    kind: Snapshot
