apiVersion: core.kubestash.com/v1alpha1
kind: BackupConfiguration
metadata:
  name: pvc-backup
  namespace: demo
spec:
  target:
    apiGroup:
    kind: PersistentVolumeClaim
    name: backup-target-pvc
    namespace: demo
  backends:
  - name: gcs-storage
    storageRef:
      namespace: demo
      name: s3-storage
    retentionPolicy:
      name: demo-retention
      namespace: demo
  sessions:
  - name: frequent-backup
    sessionHistoryLimit: 
    scheduler: 
      schedule: "*/5 * * * *"
    repositories: 
    - name: pvc-backup
      backend: gcs-storage
      directory: /pvc-backup
      encryptionSecret:
       name: encrypt-secret 
       namespace: demo
      deletionPolicy: Delete 
    addon:
      name: pvc-addon
      tasks:
      - name: logical-backup