apiVersion: catalog.kubedb.com/v1alpha1
kind: PostgresVersion
metadata:
  annotations:
    meta.helm.sh/release-name: kubedb
    meta.helm.sh/release-namespace: kubedb
  creationTimestamp: "2025-04-28T11:28:31Z"
  generation: 1
  labels:
    app.kubernetes.io/instance: kubedb
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: kubedb-catalog
    app.kubernetes.io/version: v2025.3.24
    helm.sh/chart: kubedb-catalog-v2025.3.24
  managedFields:
  - apiVersion: catalog.kubedb.com/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:meta.helm.sh/release-name: {}
          f:meta.helm.sh/release-namespace: {}
        f:labels:
          .: {}
          f:app.kubernetes.io/instance: {}
          f:app.kubernetes.io/managed-by: {}
          f:app.kubernetes.io/name: {}
          f:app.kubernetes.io/version: {}
          f:helm.sh/chart: {}
      f:spec:
        .: {}
        f:coordinator:
          .: {}
          f:image: {}
        f:db:
          .: {}
          f:baseOS: {}
          f:image: {}
        f:distribution: {}
        f:exporter:
          .: {}
          f:image: {}
        f:initContainer:
          .: {}
          f:image: {}
        f:podSecurityPolicies:
          .: {}
          f:databasePolicyName: {}
        f:securityContext:
          .: {}
          f:runAsAnyNonRoot: {}
          f:runAsUser: {}
        f:stash:
          .: {}
          f:addon:
            .: {}
            f:backupTask:
              .: {}
              f:name: {}
            f:restoreTask:
              .: {}
              f:name: {}
        f:ui: {}
        f:updateConstraints:
          .: {}
          f:allowlist: {}
        f:version: {}
    manager: helm
    operation: Update
    time: "2025-04-28T11:28:31Z"
  name: 10.23-bullseye
  resourceVersion: "59417"
  uid: e1db68e5-ff52-46a7-95cb-96eb317adcc7
spec:
  coordinator:
    image: ghcr.io/kubedb/pg-coordinator:v0.37.0
  db:
    baseOS: bullseye
    image: ghcr.io/appscode-images/postgres:10.23-bullseye
  distribution: Official
  exporter:
    image: prometheuscommunity/postgres-exporter:v0.15.0
  initContainer:
    image: ghcr.io/kubedb/postgres-init:0.17.1
  podSecurityPolicies:
    databasePolicyName: ""
  securityContext:
    runAsAnyNonRoot: true
    runAsUser: 999
  stash:
    addon:
      backupTask:
        name: postgres-backup-10.14
      restoreTask:
        name: postgres-restore-10.14
  ui:
  - name: pgadmin
    version: v2024.4.27
  - name: dbgate
    version: v2024.4.27
  updateConstraints:
    allowlist:
    - '>= 10.23, <= 16.8'
  version: "10.23"
