apiVersion: events.k8s.io/v1
deprecatedCount: 1
deprecatedFirstTimestamp: "2025-04-28T11:28:23Z"
deprecatedLastTimestamp: "2025-04-28T11:28:23Z"
deprecatedSource:
  component: kubelet
  host: kind-control-plane
eventTime: null
kind: Event
metadata:
  creationTimestamp: "2025-04-28T11:28:23Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:count: {}
      f:firstTimestamp: {}
      f:involvedObject: {}
      f:lastTimestamp: {}
      f:message: {}
      f:reason: {}
      f:reportingComponent: {}
      f:reportingInstance: {}
      f:source:
        f:component: {}
        f:host: {}
      f:type: {}
    manager: kubelet
    operation: Update
    time: "2025-04-28T11:28:23Z"
  name: kubedb-kubedb-crd-manager-lgvb2.183a77f5fe382814
  namespace: kubedb
  resourceVersion: "59111"
  uid: b92e1958-e915-48a2-9c78-520d1eddf924
note: 'Created container: verifier'
reason: Created
regarding:
  apiVersion: v1
  fieldPath: spec.containers{verifier}
  kind: Pod
  name: kubedb-kubedb-crd-manager-lgvb2
  namespace: kubedb
  resourceVersion: "58972"
  uid: 204d0c39-138b-49f5-b55d-b5b885cbe06b
reportingController: kubelet
reportingInstance: kind-control-plane
type: Normal
