apiVersion: events.k8s.io/v1
deprecatedCount: 1
deprecatedFirstTimestamp: "2025-04-28T11:28:31Z"
deprecatedLastTimestamp: "2025-04-28T11:28:31Z"
deprecatedSource:
  component: kubelet
  host: kind-control-plane
eventTime: null
kind: Event
metadata:
  creationTimestamp: "2025-04-28T11:28:31Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:count: {}
      f:firstTimestamp: {}
      f:involvedObject: {}
      f:lastTimestamp: {}
      f:message: {}
      f:reason: {}
      f:reportingComponent: {}
      f:reportingInstance: {}
      f:source:
        f:component: {}
        f:host: {}
      f:type: {}
    manager: kubelet
    operation: Update
    time: "2025-04-28T11:28:31Z"
  name: kubedb-kubedb-ops-manager-0.183a77f7c8312ce1
  namespace: kubedb
  resourceVersion: "59496"
  uid: 775de73d-74aa-4e9b-a5ee-280f4e26ca8a
note: Container image "ghcr.io/appscode/kubectl-nonroot:1.31" already present on machine
reason: Pulled
regarding:
  apiVersion: v1
  fieldPath: spec.initContainers{wait}
  kind: Pod
  name: kubedb-kubedb-ops-manager-0
  namespace: kubedb
  resourceVersion: "59324"
  uid: a47b01a6-24be-4929-96bc-b156395bf109
reportingController: kubelet
reportingInstance: kind-control-plane
type: Normal
