apiVersion: storage.kubestash.com/v1alpha1
kind: BackupStorage
metadata:
  name: gcs-storage
  namespace: demo
spec:
  storage:
    provider: local
    local:
      mountPath: /target/mountpath/pvc2
      persistentVolumeClaim:
        claimName: backup-target-pvc
  usagePolicy:
    allowedNamespaces:
      from: All
  default: false 
  deletionPolicy: WipeOut
  # runtimeSettings:
  #   pod:
  #     securityContext:
  #       fsGroup: 65535
        