apiVersion: v1
kind: Endpoints
metadata:
  annotations:
    endpoints.kubernetes.io/last-change-trigger-time: "2025-04-28T11:28:51Z"
  creationTimestamp: "2025-04-28T11:28:31Z"
  labels:
    app.kubernetes.io/instance: kubedb
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: petset
    app.kubernetes.io/version: v0.0.10
    helm.sh/chart: petset-v2025.3.14
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:endpoints.kubernetes.io/last-change-trigger-time: {}
        f:labels:
          .: {}
          f:app.kubernetes.io/instance: {}
          f:app.kubernetes.io/managed-by: {}
          f:app.kubernetes.io/name: {}
          f:app.kubernetes.io/version: {}
          f:helm.sh/chart: {}
      f:subsets: {}
    manager: kube-controller-manager
    operation: Update
    time: "2025-04-28T11:28:51Z"
  name: kubedb-petset
  namespace: kubedb
  resourceVersion: "59566"
  uid: e299ded8-b24f-40db-9339-33e59dc87200
subsets:
- addresses:
  - ip: 10.244.0.17
    nodeName: kind-control-plane
    targetRef:
      kind: Pod
      name: kubedb-petset-57f469fc58-lsnj6
      namespace: kubedb
      uid: 36260d49-98bf-4259-a798-50f1e20e59be
  ports:
  - name: https
    port: 9443
    protocol: TCP
  - name: metrics
    port: 8443
    protocol: TCP
