apiVersion: v1
kind: Endpoints
metadata:
  annotations:
    endpoints.kubernetes.io/last-change-trigger-time: "2025-04-28T11:28:58Z"
  creationTimestamp: "2025-04-28T11:28:31Z"
  labels:
    app.kubernetes.io/instance: kubedb
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: sidekick
    app.kubernetes.io/version: v0.0.11
    helm.sh/chart: sidekick-v2025.3.14
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:endpoints.kubernetes.io/last-change-trigger-time: {}
        f:labels:
          .: {}
          f:app.kubernetes.io/instance: {}
          f:app.kubernetes.io/managed-by: {}
          f:app.kubernetes.io/name: {}
          f:app.kubernetes.io/version: {}
          f:helm.sh/chart: {}
      f:subsets: {}
    manager: kube-controller-manager
    operation: Update
    time: "2025-04-28T11:28:58Z"
  name: kubedb-sidekick
  namespace: kubedb
  resourceVersion: "59586"
  uid: 2546679e-7638-4f3d-ad87-2d7751d9d416
subsets:
- addresses:
  - ip: 10.244.0.19
    nodeName: kind-control-plane
    targetRef:
      kind: Pod
      name: kubedb-sidekick-64557ff5dd-g2xpt
      namespace: kubedb
      uid: 12eb5a56-97d4-446e-896d-52b21d229995
  ports:
  - name: https
    port: 9443
    protocol: TCP
  - name: metrics
    port: 8443
    protocol: TCP
