apiVersion: v1
kind: Endpoints
metadata:
  annotations:
    endpoints.kubernetes.io/last-change-trigger-time: "2025-04-28T11:29:40Z"
  creationTimestamp: "2025-04-28T11:28:31Z"
  labels:
    app.kubernetes.io/instance: kubedb
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: kubedb-ops-manager
    app.kubernetes.io/version: v0.40.1
    helm.sh/chart: kubedb-ops-manager-v0.40.0
    service.kubernetes.io/headless: ""
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:endpoints.kubernetes.io/last-change-trigger-time: {}
        f:labels:
          .: {}
          f:app.kubernetes.io/instance: {}
          f:app.kubernetes.io/managed-by: {}
          f:app.kubernetes.io/name: {}
          f:app.kubernetes.io/version: {}
          f:helm.sh/chart: {}
          f:service.kubernetes.io/headless: {}
      f:subsets: {}
    manager: kube-controller-manager
    operation: Update
    time: "2025-04-28T11:29:40Z"
  name: kubedb-kubedb-ops-manager-headless
  namespace: kubedb
  resourceVersion: "59671"
  uid: 6c0fddd6-582f-4ac5-915d-394d39300d00
subsets:
- addresses:
  - hostname: kubedb-kubedb-ops-manager-0
    ip: 10.244.0.20
    nodeName: kind-control-plane
    targetRef:
      kind: Pod
      name: kubedb-kubedb-ops-manager-0
      namespace: kubedb
      uid: a47b01a6-24be-4929-96bc-b156395bf109
  ports:
  - name: probes
    port: 8081
    protocol: TCP
  - name: metrics
    port: 8080
    protocol: TCP
