apiVersion: v1
kind: Endpoints
metadata:
  annotations:
    endpoints.kubernetes.io/last-change-trigger-time: "2025-04-28T11:30:24Z"
  creationTimestamp: "2025-04-28T11:28:31Z"
  labels:
    app.kubernetes.io/instance: kubedb
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: kubedb-autoscaler
    app.kubernetes.io/version: v0.38.0
    helm.sh/chart: kubedb-autoscaler-v0.38.0
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:endpoints.kubernetes.io/last-change-trigger-time: {}
        f:labels:
          .: {}
          f:app.kubernetes.io/instance: {}
          f:app.kubernetes.io/managed-by: {}
          f:app.kubernetes.io/name: {}
          f:app.kubernetes.io/version: {}
          f:helm.sh/chart: {}
      f:subsets: {}
    manager: kube-controller-manager
    operation: Update
    time: "2025-04-28T11:30:24Z"
  name: kubedb-kubedb-autoscaler
  namespace: kubedb
  resourceVersion: "59748"
  uid: d11b8a20-ae0b-421a-88c0-4868a7066da6
subsets:
- addresses:
  - ip: 10.244.0.21
    nodeName: kind-control-plane
    targetRef:
      kind: Pod
      name: kubedb-kubedb-autoscaler-0
      namespace: kubedb
      uid: 5ba97215-8a73-4492-9516-073c5cd70b49
  ports:
  - name: metrics
    port: 8080
    protocol: TCP
