apiVersion: catalog.kubedb.com/v1alpha1
kind: MySQLVersion
metadata:
  annotations:
    meta.helm.sh/release-name: kubedb
    meta.helm.sh/release-namespace: kubedb
  creationTimestamp: "2025-04-28T11:28:31Z"
  generation: 1
  labels:
    app.kubernetes.io/instance: kubedb
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: kubedb-catalog
    app.kubernetes.io/version: v2025.3.24
    helm.sh/chart: kubedb-catalog-v2025.3.24
  managedFields:
  - apiVersion: catalog.kubedb.com/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:meta.helm.sh/release-name: {}
          f:meta.helm.sh/release-namespace: {}
        f:labels:
          .: {}
          f:app.kubernetes.io/instance: {}
          f:app.kubernetes.io/managed-by: {}
          f:app.kubernetes.io/name: {}
          f:app.kubernetes.io/version: {}
          f:helm.sh/chart: {}
      f:spec:
        .: {}
        f:archiver:
          .: {}
          f:addon:
            .: {}
            f:name: {}
            f:tasks:
              .: {}
              f:manifestBackup:
                .: {}
                f:name: {}
              f:manifestRestore:
                .: {}
                f:name: {}
              f:volumeSnapshot:
                .: {}
                f:name: {}
          f:walg:
            .: {}
            f:image: {}
        f:coordinator:
          .: {}
          f:image: {}
        f:db:
          .: {}
          f:image: {}
        f:distribution: {}
        f:exporter:
          .: {}
          f:image: {}
        f:gitSyncer:
          .: {}
          f:image: {}
        f:initContainer:
          .: {}
          f:image: {}
        f:podSecurityPolicies:
          .: {}
          f:databasePolicyName: {}
        f:replicationModeDetector:
          .: {}
          f:image: {}
        f:securityContext:
          .: {}
          f:runAsUser: {}
        f:stash:
          .: {}
          f:addon:
            .: {}
            f:backupTask:
              .: {}
              f:name: {}
            f:restoreTask:
              .: {}
              f:name: {}
        f:ui: {}
        f:updateConstraints:
          .: {}
          f:allowlist:
            .: {}
            f:groupReplication: {}
            f:standalone: {}
          f:denylist:
            .: {}
            f:groupReplication: {}
            f:standalone: {}
        f:version: {}
    manager: helm
    operation: Update
    time: "2025-04-28T11:28:31Z"
  name: 8.4.3
  resourceVersion: "59408"
  uid: e316759a-3352-416b-9769-1afec47ca91a
spec:
  archiver:
    addon:
      name: mysql-addon
      tasks:
        manifestBackup:
          name: manifest-backup
        manifestRestore:
          name: manifest-restore
        volumeSnapshot:
          name: volume-snapshot
    walg:
      image: ghcr.io/kubedb/mysql-archiver:v0.14.0_8.4.3
  coordinator:
    image: ghcr.io/kubedb/mysql-coordinator:v0.31.0
  db:
    image: ghcr.io/appscode-images/mysql:8.4.3-oracle
  distribution: Official
  exporter:
    image: ghcr.io/kubedb/mysqld-exporter:v0.13.1
  gitSyncer:
    image: registry.k8s.io/git-sync/git-sync:v4.2.1
  initContainer:
    image: ghcr.io/kubedb/mysql-init:8.4.3-v3
  podSecurityPolicies:
    databasePolicyName: ""
  replicationModeDetector:
    image: ghcr.io/kubedb/replication-mode-detector:v0.40.0
  securityContext:
    runAsUser: 999
  stash:
    addon:
      backupTask:
        name: mysql-backup-8.0.21
      restoreTask:
        name: mysql-restore-8.0.21
  ui:
  - name: phpmyadmin
    version: v2024.4.27
  updateConstraints:
    allowlist:
      groupReplication:
      - '>= 8.4.3, <= 9.1.0'
      standalone:
      - '>= 8.4.3, <= 9.1.0'
    denylist:
      groupReplication:
      - < 8.4.3
      standalone:
      - < 8.4.3
  version: 8.4.3
