apiVersion: core.kubestash.com/v1alpha1
kind: BackupConfiguration
metadata:
  name: selector-resources-backup
  namespace: demo
spec:
  backends:
    - name: aws-backend
      storageRef:
        namespace: demo
        name: aws-storage
      retentionPolicy:
        name: demo-retention
        namespace: demo
  sessions:
    - name: frequent-backup
      sessionHistoryLimit: 1
      scheduler:
        schedule: "*/5 * * * *"
        jobTemplate:
          backoffLimit: 1
      repositories:
        - name: selector-aws-repository
          backend: aws-backend
          directory: /cluster-manifests-selector
          encryptionSecret:
            name: encrypt-secret
            namespace: demo
          deletionPolicy: Retain
      addon:
        name: kubedump-addon
        tasks:
          - name: manifest-backup
            params:
              IncludeClusterResources: "true"
              IncludeNamespaces: "demo"
        jobTemplate:
          spec:
            serviceAccountName: cluster-resource-reader-writter