apiVersion: stash.appscode.com/v1beta1
kind: BackupConfiguration
metadata:
  name: mongo-backup
  namespace: demo
spec:
  repository:
    name: s3-repo
  schedule: "*/5 * * * *"
  target:
    ref:
      apiVersion: appcatalog.appscode.com/v1alpha1
      kind: AppBinding
      name: sample-mgo-rs
  retentionPolicy:
    name: 'keep-last-5'
    keepLast: 5
    prune: true