apiVersion: kubedb.com/v1
kind: MongoDB
metadata:
  name: sample-mgo-rs
  namespace: demo
spec:
  version: "7.0.5"
  replicas: 3
  replicaSet:
    name: rs0
  storage:
    # storageClassName: "standard"
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
  deletionPolicy: WipeOut