apiVersion: stash.appscode.com/v1beta1
kind: BackupConfiguration
metadata:
  name: ss-backup
  namespace: demo
spec:
  repository:
    name: s3-repo
    namespace: demo
  runtimeSettings:
    container:
      resources:
        limits:
          cpu: 1
          memory: 1Gi
        requests:
          cpu: 200m
          memory: 1Gi
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
          - ALL
        runAsNonRoot: true
        runAsUser: 999
        seccompProfile:
          type: RuntimeDefault
    pod:
      securityContext:  ## will not set as for STS backup. 
        runAsGroup: 777
        runAsUser: 777
        seccompProfile:
          type: RuntimeDefault
  schedule: "*/5 * * * *"
  target:
    ref:
      apiVersion: apps/v1
      kind: StatefulSet
      name: stash-demo
    volumeMounts:
    - name: source-data
      mountPath: /source/data
    paths:
    - /source/data
  retentionPolicy:
    name: 'keep-last-5'
    keepLast: 5
    prune: true