➤ kubectl get pods -n demo stash-demo-1 -o yaml
apiVersion: v1
kind: Pod
metadata:
  annotations:
    stash.appscode.com/last-applied-restore-invoker-hash: "1490058473928210959"
  creationTimestamp: "2025-05-12T13:14:01Z"
  generateName: stash-demo-
  labels:
    app: stash-demo
    apps.kubernetes.io/pod-index: "1"
    controller-revision-hash: stash-demo-545fbd49fb
    statefulset.kubernetes.io/pod-name: stash-demo-1
  name: stash-demo-1
  namespace: demo
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: StatefulSet
    name: stash-demo
    uid: e7c42f58-7a80-4426-bd31-efa2ed31bdd4
  resourceVersion: "32177"
  uid: 1ac79dd0-8d46-4aed-98f1-9c4b6611d0c6
spec:
  containers:
  - command:
    - /bin/sh
    - -c
    - echo $(POD_NAME) > /source/data/data.txt && sleep 3000
    env:
    - name: POD_NAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.name
    image: busybox
    imagePullPolicy: IfNotPresent
    name: busybox
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /source/data
      name: source-data
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-sxg5w
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  hostname: stash-demo-1
  initContainers:
  - args:
    - restore
    - --invoker-kind=RestoreSession
    - --invoker-name=ss-restore
    - --target-name=stash-demo
    - --target-namespace=demo
    - --target-kind=StatefulSet
    - --enable-cache=true
    - --max-connections=0
    - --metrics-enabled=true
    - --pushgateway-url=http://stash-stash-enterprise.stash.svc:56789
    - --use-kubeapiserver-fqdn-for-aks=true
    - --logtostderr=true
    - --alsologtostderr=false
    - --v=3
    - --stderrthreshold=2
    env:
    - name: NODE_NAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: spec.nodeName
    - name: POD_NAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.name
    - name: GOGC
      value: "20"
    image: ghcr.io/stashed/stash-enterprise:v0.39.0
    imagePullPolicy: IfNotPresent
    name: stash-init
    resources:
      limits:
        cpu: "1"
        memory: 1Gi
      requests:
        cpu: 200m
        memory: 1Gi
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
      runAsGroup: 999
      runAsNonRoot: true
      runAsUser: 999
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /stash-tmp
      name: stash-tmp-dir
    - mountPath: /source/data
      name: source-data
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-sxg5w
      readOnly: true
  nodeName: kind-control-plane
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  subdomain: headless
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: source-data
    persistentVolumeClaim:
      claimName: source-data-stash-demo-1
  - emptyDir: {}
    name: stash-tmp-dir
  - name: kube-api-access-sxg5w
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2025-05-12T13:14:02Z"
    status: "True"
    type: PodReadyToStartContainers
  - lastProbeTime: null
    lastTransitionTime: "2025-05-12T13:14:01Z"
    message: 'containers with incomplete status: [stash-init]'
    reason: ContainersNotInitialized
    status: "False"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2025-05-12T13:14:01Z"
    message: 'containers with unready status: [busybox]'
    reason: ContainersNotReady
    status: "False"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2025-05-12T13:14:01Z"
    message: 'containers with unready status: [busybox]'
    reason: ContainersNotReady
    status: "False"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2025-05-12T13:14:01Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - image: busybox
    imageID: ""
    lastState: {}
    name: busybox
    ready: false
    restartCount: 0
    started: false
    state:
      waiting:
        reason: PodInitializing
    volumeMounts:
    - mountPath: /source/data
      name: source-data
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-sxg5w
      readOnly: true
      recursiveReadOnly: Disabled
  hostIP: 172.18.0.2
  hostIPs:
  - ip: 172.18.0.2
  initContainerStatuses:
  - containerID: containerd://406b6b8f9c7d0720bdf11a91827ccb27ddcc7ff3aa8038aa46cd752b5314ab99
    image: ghcr.io/stashed/stash-enterprise:v0.39.0
    imageID: ghcr.io/stashed/stash-enterprise@sha256:86f8fb23790454ca93a9d1affa70635aed172da0eb08038a0a6eab8f0187ab66
    lastState: {}
    name: stash-init
    ready: false
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2025-05-12T13:14:01Z"
    volumeMounts:
    - mountPath: /stash-tmp
      name: stash-tmp-dir
    - mountPath: /source/data
      name: source-data
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-sxg5w
      readOnly: true
      recursiveReadOnly: Disabled
  phase: Pending
  podIP: 10.244.0.32
  podIPs:
  - ip: 10.244.0.32
  qosClass: Burstable
  startTime: "2025-05-12T13:14:01Z"
