apiVersion: v1
data:
  app.properties: |
    greeting.message=Hello, World!
    app.version=1.0.0
kind: ConfigMap
metadata:
  annotations: {}
  labels:
    app: my-app
  name: my-config
  namespace: demo
