apiVersion: core.kubestash.com/v1alpha1
kind: BackupConfiguration
metadata:
  name: statefulset-backup
  namespace: demo
spec:
  target:
    apiGroup: apps
    kind: StatefulSet
    namespace: demo
    name: kubestash-statefulset
  backends:
    - name: gcs-storage
      storageRef:
        namespace: demo
        name: gcs-storage
      retentionPolicy:
        name: demo-retention
        namespace: demo
    - name: nfs-storage
      storageRef:
        namespace: demo
        name: nfs-storage
      retentionPolicy:
        name: demo-retention
        namespace: demo
  sessions:
    - name: workload-backup
      sessionHistoryLimit: 50
      scheduler: # CronJob specification
        schedule: "*/5 * * * *"
        jobTemplate: # Comes from batch/v1 JobTemplateSpec
          backoffLimit: 1
      repositories: # volume & volumeMount strategy.
        - name: statefulset-demo-gcs
          backend: gcs-storage
          directory: /statefulset-gcs
          encryptionSecret:
           name: encrypt-secret # some addon may not support encryption
           namespace: demo
          deletionPolicy: WipeOut
        - name: statefulset-demo-nfs
          backend: nfs-storage
          directory: /statefulset-nfs
          encryptionSecret:
           name: encrypt-secret # some addon may not support encryption
           namespace: demo
          deletionPolicy: WipeOut  
      addon:
        name: workload-addon
        tasks:
          - name: logical-backup 
            params:
             paths: /source/data,/source/config
        jobTemplate:
          spec: 
            securityContext: 
              runAsUser: 0
