apiVersion: core.kubestash.com/v1alpha1
kind: RestoreSession
metadata:
  name: statefulset-restoresession
  namespace: demo
spec:
  target:
    apiGroup: apps
    kind: StatefulSet
    namespace: demo
    name: kubestash-restore-statefulset
  dataSource:
    repository: statefulset-demo-gcs
    snapshot: latest
    encryptionSecret:
      name: encrypt-secret # some addon may not support encryption
      namespace: demo
  addon:
    name: workload-addon
    tasks:
    - name: logical-backup-restore
      addonVolumes:
      - name: ${RESTIC_CACHE_VOLUME}
        source:
          # persistentVolumeClaim:
          #   claimName: backup-target-pvc
          volumeClaimTemplate:
            spec:
              accessModes:
              - ReadWriteOnce
              resources:
                requests:
                  storage: 1Gi
