apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: xx
  namespace: demo
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
---

apiVersion: v1
kind: Pod
metadata:
  name: statefulset-backup-workload-backup-1742378090-0-rkz8x
  namespace: demo
spec:
  containers:
  - args:
    - backup
    - --namespace=demo
    - --backupsession=statefulset-backup-workload-backup-1742378090
    - --enable-cache=true
    - --scratch-dir=/kubestash-tmp
    - --paths=/source/data,/source/config
    - --exclude=
    env:
    - name: COMPONENT_NAME
      value: dump-pod-0
    image: ghcr.io/kubestash/workload:v0.15.0
    imagePullPolicy: IfNotPresent
    name: logical-backup-0
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /kubestash-tmp
      name: kubestash-tmp-volume
  # dnsPolicy: ClusterFirst
  # enableServiceLinks: true
  nodeName: kind-control-plane
  priority: 0
  restartPolicy: Never
  terminationGracePeriodSeconds: 30
  volumes:
  - name: kubestash-tmp-volume
    persistentVolumeClaim:
      claimName: xx
