apiVersion: flowcontrol.apiserver.k8s.io/v1
kind: FlowSchema
metadata:
  annotations:
    apf.kubernetes.io/autoupdate-spec: "true"
  creationTimestamp: "2025-04-25T10:16:38Z"
  generation: 1
  managedFields:
  - apiVersion: flowcontrol.apiserver.k8s.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        f:conditions:
          k:{"type":"Dangling"}:
            .: {}
            f:lastTransitionTime: {}
            f:message: {}
            f:reason: {}
            f:status: {}
            f:type: {}
    manager: api-priority-and-fairness-config-consumer-v1
    operation: Apply
    subresource: status
    time: "2025-04-25T10:16:38Z"
  - apiVersion: flowcontrol.apiserver.k8s.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:apf.kubernetes.io/autoupdate-spec: {}
      f:spec:
        f:distinguisherMethod:
          .: {}
          f:type: {}
        f:matchingPrecedence: {}
        f:priorityLevelConfiguration:
          f:name: {}
        f:rules: {}
    manager: api-priority-and-fairness-config-producer-v1
    operation: Update
    time: "2025-04-25T10:16:38Z"
  name: global-default
  resourceVersion: "59"
  uid: 47d349af-66a7-4252-bae2-1bd5af75cde9
spec:
  distinguisherMethod:
    type: ByUser
  matchingPrecedence: 9900
  priorityLevelConfiguration:
    name: global-default
  rules:
  - nonResourceRules:
    - nonResourceURLs:
      - '*'
      verbs:
      - '*'
    resourceRules:
    - apiGroups:
      - '*'
      clusterScope: true
      namespaces:
      - '*'
      resources:
      - '*'
      verbs:
      - '*'
    subjects:
    - group:
        name: system:unauthenticated
      kind: Group
    - group:
        name: system:authenticated
      kind: Group
status:
  conditions:
  - lastTransitionTime: "2025-04-25T10:16:38Z"
    message: This FlowSchema references the PriorityLevelConfiguration object named
      "global-default" and it exists
    reason: Found
    status: "False"
    type: Dangling
