apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: "2025-04-25T12:56:33Z"
  generation: 1
  labels:
    app.kubernetes.io/name: kubedb
    velero.io/backup-name: kubedb-backup
    velero.io/restore-name: kubedb-backup-restore
  managedFields:
  - apiVersion: apiextensions.k8s.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:labels:
          .: {}
          f:app.kubernetes.io/name: {}
      f:spec:
        f:conversion:
          .: {}
          f:strategy: {}
        f:group: {}
        f:names:
          f:categories: {}
          f:kind: {}
          f:listKind: {}
          f:plural: {}
          f:shortNames: {}
          f:singular: {}
        f:scope: {}
        f:versions: {}
    manager: helm
    operation: Update
    time: "2025-04-25T12:17:39Z"
  - apiVersion: apiextensions.k8s.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        f:acceptedNames:
          f:categories: {}
          f:kind: {}
          f:listKind: {}
          f:plural: {}
          f:shortNames: {}
          f:singular: {}
        f:conditions:
          k:{"type":"Established"}:
            .: {}
            f:lastTransitionTime: {}
            f:message: {}
            f:reason: {}
            f:status: {}
            f:type: {}
          k:{"type":"NamesAccepted"}:
            .: {}
            f:lastTransitionTime: {}
            f:message: {}
            f:reason: {}
            f:status: {}
            f:type: {}
    manager: kube-apiserver
    operation: Update
    subresource: status
    time: "2025-04-25T12:17:39Z"
  name: druidversions.catalog.kubedb.com
  resourceVersion: "20484"
  uid: 58e97ebb-6635-4f20-93aa-fda7b5eed8ab
spec:
  conversion:
    strategy: None
  group: catalog.kubedb.com
  names:
    categories:
    - catalog
    - kubedb
    - appscode
    kind: DruidVersion
    listKind: DruidVersionList
    plural: druidversions
    shortNames:
    - drversion
    singular: druidversion
  scope: Cluster
  versions:
  - additionalPrinterColumns:
    - jsonPath: .spec.version
      name: Version
      type: string
    - jsonPath: .spec.db.image
      name: DB_IMAGE
      type: string
    - jsonPath: .spec.deprecated
      name: Deprecated
      type: boolean
    - jsonPath: .metadata.creationTimestamp
      name: Age
      type: date
    name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            type: string
          kind:
            type: string
          metadata:
            type: object
          spec:
            properties:
              db:
                properties:
                  image:
                    type: string
                required:
                - image
                type: object
              deprecated:
                type: boolean
              initContainer:
                properties:
                  image:
                    type: string
                required:
                - image
                type: object
              securityContext:
                properties:
                  runAsUser:
                    format: int64
                    type: integer
                type: object
              ui:
                items:
                  properties:
                    disable:
                      type: boolean
                    name:
                      type: string
                    values:
                      x-kubernetes-preserve-unknown-fields: true
                    version:
                      type: string
                  required:
                  - name
                  type: object
                type: array
              version:
                type: string
            required:
            - db
            - initContainer
            - version
            type: object
        type: object
    served: true
    storage: true
    subresources: {}
status:
  acceptedNames:
    categories:
    - catalog
    - kubedb
    - appscode
    kind: DruidVersion
    listKind: DruidVersionList
    plural: druidversions
    shortNames:
    - drversion
    singular: druidversion
  conditions:
  - lastTransitionTime: "2025-04-25T12:56:33Z"
    message: no conflicts found
    reason: NoConflicts
    status: "True"
    type: NamesAccepted
  - lastTransitionTime: "2025-04-25T12:56:33Z"
    message: the initial names have been accepted
    reason: InitialNamesAccepted
    status: "True"
    type: Established
  storedVersions:
  - v1alpha1
