apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: "2025-04-25T12:56:46Z"
  generation: 1
  labels:
    app.kubernetes.io/name: kubedb
    velero.io/backup-name: kubedb-backup
    velero.io/restore-name: kubedb-backup-restore
  managedFields:
  - apiVersion: apiextensions.k8s.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:labels:
          .: {}
          f:app.kubernetes.io/name: {}
      f:spec:
        f:conversion:
          .: {}
          f:strategy: {}
        f:group: {}
        f:names:
          f:categories: {}
          f:kind: {}
          f:listKind: {}
          f:plural: {}
          f:shortNames: {}
          f:singular: {}
        f:scope: {}
        f:versions: {}
    manager: helm
    operation: Update
    time: "2025-04-25T12:17:39Z"
  - apiVersion: apiextensions.k8s.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        f:acceptedNames:
          f:categories: {}
          f:kind: {}
          f:listKind: {}
          f:plural: {}
          f:shortNames: {}
          f:singular: {}
        f:conditions:
          k:{"type":"Established"}:
            .: {}
            f:lastTransitionTime: {}
            f:message: {}
            f:reason: {}
            f:status: {}
            f:type: {}
          k:{"type":"NamesAccepted"}:
            .: {}
            f:lastTransitionTime: {}
            f:message: {}
            f:reason: {}
            f:status: {}
            f:type: {}
    manager: kube-apiserver
    operation: Update
    subresource: status
    time: "2025-04-25T12:17:39Z"
  name: mariadbversions.catalog.kubedb.com
  resourceVersion: "20581"
  uid: 2a4b6be8-7c5a-4013-bcd8-674daf892bdc
spec:
  conversion:
    strategy: None
  group: catalog.kubedb.com
  names:
    categories:
    - catalog
    - kubedb
    - appscode
    kind: MariaDBVersion
    listKind: MariaDBVersionList
    plural: mariadbversions
    shortNames:
    - mdversion
    singular: mariadbversion
  scope: Cluster
  versions:
  - additionalPrinterColumns:
    - jsonPath: .spec.version
      name: Version
      type: string
    - jsonPath: .spec.db.image
      name: DB_IMAGE
      type: string
    - jsonPath: .spec.deprecated
      name: Deprecated
      type: boolean
    - jsonPath: .metadata.creationTimestamp
      name: Age
      type: date
    name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            type: string
          kind:
            type: string
          metadata:
            type: object
          spec:
            properties:
              archiver:
                properties:
                  addon:
                    properties:
                      name:
                        enum:
                        - mongodb-addon
                        - postgres-addon
                        - mysql-addon
                        - mariadb-addon
                        - mssqlserver-addon
                        type: string
                      tasks:
                        properties:
                          fullBackup:
                            properties:
                              name:
                                type: string
                            required:
                            - name
                            type: object
                          fullBackupRestore:
                            properties:
                              name:
                                type: string
                            required:
                            - name
                            type: object
                          manifestBackup:
                            properties:
                              name:
                                type: string
                            required:
                            - name
                            type: object
                          manifestRestore:
                            properties:
                              name:
                                type: string
                            required:
                            - name
                            type: object
                          volumeSnapshot:
                            properties:
                              name:
                                type: string
                            required:
                            - name
                            type: object
                        type: object
                    type: object
                  walg:
                    properties:
                      image:
                        type: string
                    required:
                    - image
                    type: object
                type: object
              coordinator:
                properties:
                  image:
                    type: string
                required:
                - image
                type: object
              db:
                properties:
                  image:
                    type: string
                required:
                - image
                type: object
              deprecated:
                type: boolean
              exporter:
                properties:
                  image:
                    type: string
                required:
                - image
                type: object
              gitSyncer:
                properties:
                  image:
                    type: string
                required:
                - image
                type: object
              initContainer:
                properties:
                  image:
                    type: string
                required:
                - image
                type: object
              maxscale:
                properties:
                  image:
                    type: string
                  securityContext:
                    properties:
                      runAsUser:
                        format: int64
                        type: integer
                    type: object
                required:
                - image
                type: object
              podSecurityPolicies:
                properties:
                  databasePolicyName:
                    type: string
                required:
                - databasePolicyName
                type: object
              securityContext:
                properties:
                  runAsUser:
                    format: int64
                    type: integer
                type: object
              stash:
                properties:
                  addon:
                    properties:
                      backupTask:
                        properties:
                          name:
                            type: string
                          params:
                            items:
                              properties:
                                name:
                                  type: string
                                value:
                                  type: string
                              required:
                              - name
                              - value
                              type: object
                            type: array
                        required:
                        - name
                        type: object
                      restoreTask:
                        properties:
                          name:
                            type: string
                          params:
                            items:
                              properties:
                                name:
                                  type: string
                                value:
                                  type: string
                              required:
                              - name
                              - value
                              type: object
                            type: array
                        required:
                        - name
                        type: object
                    required:
                    - backupTask
                    - restoreTask
                    type: object
                type: object
              ui:
                items:
                  properties:
                    disable:
                      type: boolean
                    name:
                      type: string
                    values:
                      x-kubernetes-preserve-unknown-fields: true
                    version:
                      type: string
                  required:
                  - name
                  type: object
                type: array
              updateConstraints:
                properties:
                  allowlist:
                    items:
                      type: string
                    type: array
                  denylist:
                    items:
                      type: string
                    type: array
                type: object
              version:
                type: string
            required:
            - db
            - exporter
            - initContainer
            - podSecurityPolicies
            - version
            type: object
        type: object
    served: true
    storage: true
    subresources: {}
status:
  acceptedNames:
    categories:
    - catalog
    - kubedb
    - appscode
    kind: MariaDBVersion
    listKind: MariaDBVersionList
    plural: mariadbversions
    shortNames:
    - mdversion
    singular: mariadbversion
  conditions:
  - lastTransitionTime: "2025-04-25T12:56:46Z"
    message: no conflicts found
    reason: NoConflicts
    status: "True"
    type: NamesAccepted
  - lastTransitionTime: "2025-04-25T12:56:46Z"
    message: the initial names have been accepted
    reason: InitialNamesAccepted
    status: "True"
    type: Established
  storedVersions:
  - v1alpha1
