apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: "2025-04-25T11:13:55Z"
  generation: 3
  managedFields:
  - apiVersion: apiextensions.k8s.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:spec:
        f:conversion:
          .: {}
          f:strategy: {}
        f:group: {}
        f:names:
          f:kind: {}
          f:listKind: {}
          f:plural: {}
          f:singular: {}
        f:scope: {}
    manager: helm
    operation: Update
    time: "2025-04-25T11:13:55Z"
  - apiVersion: apiextensions.k8s.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        f:acceptedNames:
          f:kind: {}
          f:listKind: {}
          f:plural: {}
          f:singular: {}
        f:conditions:
          k:{"type":"Established"}:
            .: {}
            f:lastTransitionTime: {}
            f:message: {}
            f:reason: {}
            f:status: {}
            f:type: {}
          k:{"type":"NamesAccepted"}:
            .: {}
            f:lastTransitionTime: {}
            f:message: {}
            f:reason: {}
            f:status: {}
            f:type: {}
    manager: kube-apiserver
    operation: Update
    subresource: status
    time: "2025-04-25T11:13:55Z"
  - apiVersion: apiextensions.k8s.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:spec:
        f:versions: {}
    manager: kubedb-crd-manager
    operation: Update
    time: "2025-04-28T11:27:46Z"
  name: placementpolicies.apps.k8s.appscode.com
  resourceVersion: "58997"
  uid: 11dd4e16-251f-429d-8f54-1e0523a899c4
spec:
  conversion:
    strategy: None
  group: apps.k8s.appscode.com
  names:
    kind: PlacementPolicy
    listKind: PlacementPolicyList
    plural: placementpolicies
    singular: placementpolicy
  scope: Cluster
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        description: |-
          PlacementPolicy represents a set of pods with consistent identities.
          Identities are defined as:
            - Network: A single stable DNS and hostname.
            - Storage: As many VolumeClaims as requested.

          The PlacementPolicy guarantees that a given network identity will always
          map to the same storage identity.
        properties:
          apiVersion:
            description: |-
              APIVersion defines the versioned schema of this representation of an object.
              Servers should convert recognized schemas to the latest internal value, and
              may reject unrecognized values.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
            type: string
          kind:
            description: |-
              Kind is a string value representing the REST resource this object represents.
              Servers may infer this from the endpoint the client submits requests to.
              Cannot be updated.
              In CamelCase.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
            type: string
          metadata:
            type: object
          spec:
            description: Spec defines the desired identities of pods in this set.
            properties:
              affinity:
                description: If specified, the pod's scheduling constraints
                properties:
                  nodeAffinity:
                    description: Describes node affinity scheduling rules for the
                      pod.
                    items:
                      properties:
                        domains:
                          items:
                            properties:
                              replicas:
                                type: string
                              values:
                                items:
                                  type: string
                                type: array
                            required:
                            - replicas
                            - values
                            type: object
                          type: array
                        topologyKey:
                          type: string
                        weight:
                          default: 50
                          description: Weight associated with matching the corresponding
                            nodeSelectorTerm, in the range 1-100.
                          format: int32
                          type: integer
                        whenUnsatisfiable:
                          default: DoNotSchedule
                          type: string
                      required:
                      - domains
                      - topologyKey
                      - weight
                      - whenUnsatisfiable
                      type: object
                    type: array
                type: object
              nodeSpreadConstraint:
                properties:
                  maxSkew:
                    default: 1
                    format: int32
                    type: integer
                  whenUnsatisfiable:
                    default: DoNotSchedule
                    type: string
                required:
                - maxSkew
                - whenUnsatisfiable
                type: object
              zoneSpreadConstraint:
                properties:
                  maxSkew:
                    default: 1
                    format: int32
                    type: integer
                  whenUnsatisfiable:
                    default: DoNotSchedule
                    type: string
                required:
                - maxSkew
                - whenUnsatisfiable
                type: object
            type: object
        type: object
    served: true
    storage: true
status:
  acceptedNames:
    kind: PlacementPolicy
    listKind: PlacementPolicyList
    plural: placementpolicies
    singular: placementpolicy
  conditions:
  - lastTransitionTime: "2025-04-25T11:13:55Z"
    message: no conflicts found
    reason: NoConflicts
    status: "True"
    type: NamesAccepted
  - lastTransitionTime: "2025-04-25T11:13:55Z"
    message: the initial names have been accepted
    reason: InitialNamesAccepted
    status: "True"
    type: Established
  storedVersions:
  - v1
