apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: "2025-04-28T11:27:25Z"
  generation: 1
  managedFields:
  - apiVersion: apiextensions.k8s.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:spec:
        f:conversion:
          .: {}
          f:strategy: {}
        f:group: {}
        f:names:
          f:kind: {}
          f:listKind: {}
          f:plural: {}
          f:singular: {}
        f:scope: {}
        f:versions: {}
    manager: helm
    operation: Update
    time: "2025-04-28T11:27:25Z"
  - apiVersion: apiextensions.k8s.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        f:acceptedNames:
          f:kind: {}
          f:listKind: {}
          f:plural: {}
          f:singular: {}
        f:conditions:
          k:{"type":"Established"}:
            .: {}
            f:lastTransitionTime: {}
            f:message: {}
            f:reason: {}
            f:status: {}
            f:type: {}
          k:{"type":"NamesAccepted"}:
            .: {}
            f:lastTransitionTime: {}
            f:message: {}
            f:reason: {}
            f:status: {}
            f:type: {}
    manager: kube-apiserver
    operation: Update
    subresource: status
    time: "2025-04-28T11:27:25Z"
  name: shardconfigurations.operator.k8s.appscode.com
  resourceVersion: "58772"
  uid: 7754dcb5-66b5-4f66-b4e1-e2d682857291
spec:
  conversion:
    strategy: None
  group: operator.k8s.appscode.com
  names:
    kind: ShardConfiguration
    listKind: ShardConfigurationList
    plural: shardconfigurations
    singular: shardconfiguration
  scope: Cluster
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            type: string
          kind:
            type: string
          metadata:
            type: object
          spec:
            properties:
              controllers:
                items:
                  properties:
                    apiGroup:
                      type: string
                    kind:
                      type: string
                    name:
                      type: string
                    namespace:
                      type: string
                  required:
                  - name
                  type: object
                minItems: 1
                type: array
              resources:
                items:
                  properties:
                    apiGroup:
                      type: string
                    kind:
                      type: string
                  type: object
                minItems: 1
                type: array
            type: object
          status:
            properties:
              conditions:
                items:
                  properties:
                    lastTransitionTime:
                      format: date-time
                      type: string
                    message:
                      type: string
                    observedGeneration:
                      format: int64
                      type: integer
                    reason:
                      type: string
                    severity:
                      type: string
                    status:
                      type: string
                    type:
                      type: string
                  required:
                  - lastTransitionTime
                  - status
                  - type
                  type: object
                maxItems: 12
                type: array
                x-kubernetes-list-map-keys:
                - type
                x-kubernetes-list-type: map
              controllers:
                items:
                  properties:
                    apiGroup:
                      type: string
                    kind:
                      type: string
                    name:
                      type: string
                    namespace:
                      type: string
                    pods:
                      items:
                        type: string
                      type: array
                  required:
                  - name
                  type: object
                type: array
              phase:
                enum:
                - Pending
                - Current
                - Failed
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    kind: ShardConfiguration
    listKind: ShardConfigurationList
    plural: shardconfigurations
    singular: shardconfiguration
  conditions:
  - lastTransitionTime: "2025-04-28T11:27:25Z"
    message: no conflicts found
    reason: NoConflicts
    status: "True"
    type: NamesAccepted
  - lastTransitionTime: "2025-04-28T11:27:25Z"
    message: the initial names have been accepted
    reason: InitialNamesAccepted
    status: "True"
    type: Established
  storedVersions:
  - v1alpha1
