apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: "2025-04-25T12:57:11Z"
  generation: 1
  labels:
    app.kubernetes.io/name: kubedb
    velero.io/backup-name: kubedb-backup
    velero.io/restore-name: kubedb-backup-restore
  managedFields:
  - apiVersion: apiextensions.k8s.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:labels:
          .: {}
          f:app.kubernetes.io/name: {}
      f:spec:
        f:conversion:
          .: {}
          f:strategy: {}
        f:group: {}
        f:names:
          f:categories: {}
          f:kind: {}
          f:listKind: {}
          f:plural: {}
          f:shortNames: {}
          f:singular: {}
        f:scope: {}
        f:versions: {}
    manager: helm
    operation: Update
    time: "2025-04-25T12:17:39Z"
  - apiVersion: apiextensions.k8s.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        f:acceptedNames:
          f:categories: {}
          f:kind: {}
          f:listKind: {}
          f:plural: {}
          f:shortNames: {}
          f:singular: {}
        f:conditions:
          k:{"type":"Established"}:
            .: {}
            f:lastTransitionTime: {}
            f:message: {}
            f:reason: {}
            f:status: {}
            f:type: {}
          k:{"type":"NamesAccepted"}:
            .: {}
            f:lastTransitionTime: {}
            f:message: {}
            f:reason: {}
            f:status: {}
            f:type: {}
    manager: kube-apiserver
    operation: Update
    subresource: status
    time: "2025-04-25T12:17:39Z"
  name: zookeeperversions.catalog.kubedb.com
  resourceVersion: "20792"
  uid: ee9ec548-257c-4fab-9ba2-9fae94005c2d
spec:
  conversion:
    strategy: None
  group: catalog.kubedb.com
  names:
    categories:
    - catalog
    - kubedb
    - appscode
    kind: ZooKeeperVersion
    listKind: ZooKeeperVersionList
    plural: zookeeperversions
    shortNames:
    - zkversion
    singular: zookeeperversion
  scope: Cluster
  versions:
  - additionalPrinterColumns:
    - jsonPath: .spec.version
      name: Version
      type: string
    - jsonPath: .spec.db.image
      name: DB_IMAGE
      type: string
    - jsonPath: .spec.deprecated
      name: Deprecated
      type: boolean
    - jsonPath: .metadata.creationTimestamp
      name: Age
      type: date
    name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            type: string
          kind:
            type: string
          metadata:
            type: object
          spec:
            properties:
              coordinator:
                properties:
                  image:
                    type: string
                required:
                - image
                type: object
              db:
                properties:
                  image:
                    type: string
                required:
                - image
                type: object
              deprecated:
                type: boolean
              exporter:
                properties:
                  image:
                    type: string
                required:
                - image
                type: object
              gitSyncer:
                properties:
                  image:
                    type: string
                required:
                - image
                type: object
              initContainer:
                properties:
                  image:
                    type: string
                required:
                - image
                type: object
              podSecurityPolicies:
                properties:
                  databasePolicyName:
                    type: string
                required:
                - databasePolicyName
                type: object
              securityContext:
                properties:
                  runAsUser:
                    format: int64
                    type: integer
                type: object
              stash:
                properties:
                  addon:
                    properties:
                      backupTask:
                        properties:
                          name:
                            type: string
                          params:
                            items:
                              properties:
                                name:
                                  type: string
                                value:
                                  type: string
                              required:
                              - name
                              - value
                              type: object
                            type: array
                        required:
                        - name
                        type: object
                      restoreTask:
                        properties:
                          name:
                            type: string
                          params:
                            items:
                              properties:
                                name:
                                  type: string
                                value:
                                  type: string
                              required:
                              - name
                              - value
                              type: object
                            type: array
                        required:
                        - name
                        type: object
                    required:
                    - backupTask
                    - restoreTask
                    type: object
                type: object
              updateConstraints:
                properties:
                  allowlist:
                    items:
                      type: string
                    type: array
                  denylist:
                    items:
                      type: string
                    type: array
                type: object
              version:
                type: string
            required:
            - db
            - version
            type: object
        type: object
    served: true
    storage: true
    subresources: {}
status:
  acceptedNames:
    categories:
    - catalog
    - kubedb
    - appscode
    kind: ZooKeeperVersion
    listKind: ZooKeeperVersionList
    plural: zookeeperversions
    shortNames:
    - zkversion
    singular: zookeeperversion
  conditions:
  - lastTransitionTime: "2025-04-25T12:57:11Z"
    message: no conflicts found
    reason: NoConflicts
    status: "True"
    type: NamesAccepted
  - lastTransitionTime: "2025-04-25T12:57:11Z"
    message: the initial names have been accepted
    reason: InitialNamesAccepted
    status: "True"
    type: Established
  storedVersions:
  - v1alpha1
