apiVersion: core.kubestash.com/v1alpha1
kind: BackupConfiguration
metadata:
  name: pvc-backup
  namespace: demo
spec:
  target:
    apiGroup:
    kind: PersistentVolumeClaim
    name: backup-target-pvc
    namespace: demo
  backends:
  - name: s3-storage
    storageRef:
      namespace: demo
      name: s3-storage
    retentionPolicy:
      name: demo-retention
      namespace: demo
  sessions:
  - name: frequent-backup
    sessionHistoryLimit: 
    scheduler: 
      schedule: "*/5 * * * *"
    repositories: 
    - name: pvc-backup
      backend: s3-storage
      directory: /pvc-backup
      encryptionSecret:
       name: encrypt-secret 
       namespace: demo
      deletionPolicy: Delete 
    addon:
      name: pvc-addon
      tasks:
      - name: logical-backup
        params:
          exclude: /kubestash-data/lost+found
      # jobTemplate:
      #   spec:
      #     # serviceAccountName: irsa-test
      #     nodeSelector:
      #       kubernetes.io/hostname: ip-192-168-24-34.ec2.internal
