apiVersion: v1
kind: ServiceAccount
metadata:
  name: irsa-test
  namespace: demo
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: irsa-test
  namespace: demo
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kubestash-backup-job
subjects:
- kind: ServiceAccount
  name: irsa-test
  namespace: demo
--- 
