apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  creationTimestamp: "2025-04-25T10:16:38Z"
  labels:
    kube-aggregator.kubernetes.io/automanaged: onstart
  managedFields:
  - apiVersion: apiregistration.k8s.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:labels:
          .: {}
          f:kube-aggregator.kubernetes.io/automanaged: {}
      f:spec:
        f:group: {}
        f:groupPriorityMinimum: {}
        f:version: {}
        f:versionPriority: {}
    manager: kube-apiserver
    operation: Update
    time: "2025-04-25T10:16:38Z"
  name: v1.rbac.authorization.k8s.io
  resourceVersion: "29"
  uid: 23179825-09a5-4e2e-97b5-b5e48c3d2c99
spec:
  group: rbac.authorization.k8s.io
  groupPriorityMinimum: 17000
  version: v1
  versionPriority: 15
status:
  conditions:
  - lastTransitionTime: "2025-04-25T10:16:38Z"
    message: Local APIServices are always available
    reason: Local
    status: "True"
    type: Available
