apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  creationTimestamp: "2025-04-25T10:16:38Z"
  labels:
    kube-aggregator.kubernetes.io/automanaged: onstart
  managedFields:
  - apiVersion: apiregistration.k8s.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:labels:
          .: {}
          f:kube-aggregator.kubernetes.io/automanaged: {}
      f:spec:
        f:group: {}
        f:groupPriorityMinimum: {}
        f:version: {}
        f:versionPriority: {}
    manager: kube-apiserver
    operation: Update
    time: "2025-04-25T10:16:38Z"
  name: v1.scheduling.k8s.io
  resourceVersion: "31"
  uid: da53ea2d-e8b6-421a-9e80-8cb812215c13
spec:
  group: scheduling.k8s.io
  groupPriorityMinimum: 16600
  version: v1
  versionPriority: 15
status:
  conditions:
  - lastTransitionTime: "2025-04-25T10:16:38Z"
    message: Local APIServices are always available
    reason: Local
    status: "True"
    type: Available
