apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  creationTimestamp: "2025-04-25T12:56:43Z"
  labels:
    kube-aggregator.kubernetes.io/automanaged: "true"
  managedFields:
  - apiVersion: apiregistration.k8s.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:labels:
          .: {}
          f:kube-aggregator.kubernetes.io/automanaged: {}
      f:spec:
        f:group: {}
        f:groupPriorityMinimum: {}
        f:version: {}
        f:versionPriority: {}
    manager: kube-apiserver
    operation: Update
    time: "2025-04-25T12:56:43Z"
  name: v1alpha1.archiver.kubedb.com
  resourceVersion: "20554"
  uid: 746d4793-2168-439a-8e97-d8a864eca88c
spec:
  group: archiver.kubedb.com
  groupPriorityMinimum: 1000
  version: v1alpha1
  versionPriority: 100
status:
  conditions:
  - lastTransitionTime: "2025-04-25T12:56:43Z"
    message: Local APIServices are always available
    reason: Local
    status: "True"
    type: Available
