apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  creationTimestamp: "2025-04-25T12:56:33Z"
  labels:
    kube-aggregator.kubernetes.io/automanaged: "true"
  managedFields:
  - apiVersion: apiregistration.k8s.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:labels:
          .: {}
          f:kube-aggregator.kubernetes.io/automanaged: {}
      f:spec:
        f:group: {}
        f:groupPriorityMinimum: {}
        f:version: {}
        f:versionPriority: {}
    manager: kube-apiserver
    operation: Update
    time: "2025-04-25T12:56:33Z"
  name: v1alpha1.autoscaling.kubedb.com
  resourceVersion: "20486"
  uid: b17634a1-64a8-4557-bb3f-dc2e521e7a31
spec:
  group: autoscaling.kubedb.com
  groupPriorityMinimum: 1000
  version: v1alpha1
  versionPriority: 100
status:
  conditions:
  - lastTransitionTime: "2025-04-25T12:56:33Z"
    message: Local APIServices are always available
    reason: Local
    status: "True"
    type: Available
