apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  creationTimestamp: "2025-04-28T11:27:50Z"
  labels:
    kube-aggregator.kubernetes.io/automanaged: "true"
  managedFields:
  - apiVersion: apiregistration.k8s.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:labels:
          .: {}
          f:kube-aggregator.kubernetes.io/automanaged: {}
      f:spec:
        f:group: {}
        f:groupPriorityMinimum: {}
        f:version: {}
        f:versionPriority: {}
    manager: kube-apiserver
    operation: Update
    time: "2025-04-28T11:27:50Z"
  name: v1alpha1.gitops.kubedb.com
  resourceVersion: "59008"
  uid: cc4b34ca-642b-4f81-8e1e-a492e2b1fcc5
spec:
  group: gitops.kubedb.com
  groupPriorityMinimum: 1000
  version: v1alpha1
  versionPriority: 100
status:
  conditions:
  - lastTransitionTime: "2025-04-28T11:27:50Z"
    message: Local APIServices are always available
    reason: Local
    status: "True"
    type: Available
