apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  creationTimestamp: "2025-04-25T12:56:33Z"
  labels:
    kube-aggregator.kubernetes.io/automanaged: "true"
  managedFields:
  - apiVersion: apiregistration.k8s.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:labels:
          .: {}
          f:kube-aggregator.kubernetes.io/automanaged: {}
      f:spec:
        f:group: {}
        f:groupPriorityMinimum: {}
        f:version: {}
        f:versionPriority: {}
    manager: kube-apiserver
    operation: Update
    time: "2025-04-25T12:56:33Z"
  name: v1alpha1.elasticsearch.kubedb.com
  resourceVersion: "20491"
  uid: 1899e31f-5b5e-4572-bb6a-f42a8a14c998
spec:
  group: elasticsearch.kubedb.com
  groupPriorityMinimum: 1000
  version: v1alpha1
  versionPriority: 100
status:
  conditions:
  - lastTransitionTime: "2025-04-25T12:56:33Z"
    message: Local APIServices are always available
    reason: Local
    status: "True"
    type: Available
