apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  annotations:
    meta.helm.sh/release-name: kubedb
    meta.helm.sh/release-namespace: kubedb
  creationTimestamp: "2025-04-28T11:28:31Z"
  labels:
    app.kubernetes.io/instance: kubedb
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: sidekick
    app.kubernetes.io/version: v0.0.11
    helm.sh/chart: sidekick-v2025.3.14
  managedFields:
  - apiVersion: rbac.authorization.k8s.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:meta.helm.sh/release-name: {}
          f:meta.helm.sh/release-namespace: {}
        f:labels:
          .: {}
          f:app.kubernetes.io/instance: {}
          f:app.kubernetes.io/managed-by: {}
          f:app.kubernetes.io/name: {}
          f:app.kubernetes.io/version: {}
          f:helm.sh/chart: {}
      f:roleRef: {}
      f:subjects: {}
    manager: helm
    operation: Update
    time: "2025-04-28T11:28:31Z"
  name: kubedb-sidekick:leader-election
  namespace: kubedb
  resourceVersion: "59175"
  uid: ac89938e-207f-4086-9d9b-9e11c311a37b
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kubedb-sidekick:leader-election
subjects:
- kind: ServiceAccount
  name: kubedb-sidekick
  namespace: kubedb
