apiVersion: v1
kind: Namespace
metadata:
  name: demo-2
spec:
---
apiVersion: stash.appscode.com/v1alpha1
kind: Repository
metadata:
  name: demo-2-repo
  namespace: demo-2
spec:
  backend:
    s3:
      bucket: kubestash
      region: us-east-2
      endpoint: s3.us-east-2.amazonaws.com
      prefix: orange-multiple-backup/demo-2
    storageSecretName: aws-s3-secret
  usagePolicy:
    allowedNamespaces:
      from: All
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backup-target-pvc
  namespace: demo-2
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: demo-pod
  namespace: demo-2
spec:
  containers:
  - name: ubuntu
    image: ubuntu:22.04  # Specifying a version for reproducibility
    command: ["/bin/sh", "-c"]
    args: 
    - |
      dd if=/dev/urandom of=/target/mountpath/demo_data_500mb bs=1M count=500
      sleep infinity
    volumeMounts:
    - name: my-volume
      mountPath: /target/mountpath
  volumes:
  - name: my-volume
    persistentVolumeClaim:
      claimName: backup-target-pvc
---
apiVersion: stash.appscode.com/v1beta1
kind: BackupConfiguration
metadata:
  name: demo-2-pvc-backup
  namespace: demo-2
spec:
  task:
    name: pvc-backup
  repository:
    name: demo-2-repo
  schedule: "*/5 * * * *"
  target:
    ref:
      apiVersion: v1
      kind: PersistentVolumeClaim
      name: backup-target-pvc
  retentionPolicy:
    name: keep-last-5
    keepLast: 5
    prune: true