apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-delete-policy: before-hook-creation
  creationTimestamp: "2025-04-28T11:27:31Z"
  managedFields:
  - apiVersion: rbac.authorization.k8s.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:helm.sh/hook: {}
          f:helm.sh/hook-delete-policy: {}
      f:rules: {}
    manager: helm
    operation: Update
    time: "2025-04-28T11:27:31Z"
  name: appscode:license-checker
  resourceVersion: "58797"
  uid: d4e52465-1b21-4716-a44a-7c5832323cbb
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
- apiGroups:
  - ""
  resourceNames:
  - ace-info
  resources:
  - configmaps
  verbs:
  - get
- apiGroups:
  - proxyserver.licenses.appscode.com
  resources:
  - licenserequests
  verbs:
  - create
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
- apiGroups:
  - apps
  resources:
  - deployments
  - replicasets
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - get
  - list
  - create
  - patch
