apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-delete-policy: before-hook-creation
  creationTimestamp: "2025-04-28T11:27:31Z"
  labels:
    rbac.authorization.k8s.io/aggregate-to-view: "true"
  managedFields:
  - apiVersion: rbac.authorization.k8s.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:helm.sh/hook: {}
          f:helm.sh/hook-delete-policy: {}
        f:labels:
          .: {}
          f:rbac.authorization.k8s.io/aggregate-to-view: {}
      f:rules: {}
    manager: helm
    operation: Update
    time: "2025-04-28T11:27:31Z"
  name: appscode:petset:view
  resourceVersion: "58832"
  uid: ba17ef83-29d5-4127-b8fd-1e5155a1d936
rules:
- apiGroups:
  - apps.k8s.appscode.com
  resources:
  - petsets
  - placementpolicies
  verbs:
  - get
  - list
  - watch
