apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-delete-policy: before-hook-creation
  creationTimestamp: "2025-04-28T11:27:32Z"
  labels:
    rbac.authorization.k8s.io/aggregate-to-edit: "true"
  managedFields:
  - apiVersion: rbac.authorization.k8s.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:helm.sh/hook: {}
          f:helm.sh/hook-delete-policy: {}
        f:labels:
          .: {}
          f:rbac.authorization.k8s.io/aggregate-to-edit: {}
      f:rules: {}
    manager: helm
    operation: Update
    time: "2025-04-28T11:27:32Z"
  name: appscode:sidekick:edit
  resourceVersion: "58846"
  uid: 1ae6b286-a2c6-48e9-ad82-fc90f331e177
rules:
- apiGroups:
  - apps.k8s.appscode.com
  resources:
  - sidekicks
  verbs:
  - create
  - delete
  - deletecollection
  - patch
  - update
