apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-delete-policy: before-hook-creation
  creationTimestamp: "2025-04-28T11:27:31Z"
  labels:
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
  managedFields:
  - apiVersion: rbac.authorization.k8s.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:helm.sh/hook: {}
          f:helm.sh/hook-delete-policy: {}
        f:labels:
          .: {}
          f:rbac.authorization.k8s.io/aggregate-to-admin: {}
      f:rules: {}
    manager: helm
    operation: Update
    time: "2025-04-28T11:27:31Z"
  name: appscode:metrics:admin
  resourceVersion: "58804"
  uid: e4898f4a-1d0c-4b99-88bb-ae35f5410c23
rules:
- apiGroups:
  - metrics.appscode.com
  resources:
  - '*'
  verbs:
  - '*'
