apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: "2025-04-25T11:20:24Z"
  labels:
    app.kubernetes.io/component: kubestash-cleaner
    app.kubernetes.io/managed-by: kubestash.com
    kubestash.com/invoker-name: kubedb-backup-frequent-backup-1745579828
    kubestash.com/invoker-namespace: demo
    kubestash.com/session-name: frequent-backup
  managedFields:
  - apiVersion: rbac.authorization.k8s.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:labels:
          .: {}
          f:app.kubernetes.io/component: {}
          f:app.kubernetes.io/managed-by: {}
          f:kubestash.com/invoker-name: {}
          f:kubestash.com/invoker-namespace: {}
          f:kubestash.com/session-name: {}
      f:rules: {}
    manager: kubestash
    operation: Update
    time: "2025-04-25T11:20:24Z"
  name: kubestash-retention-policy-job
  resourceVersion: "6758"
  uid: 4acf1f0c-b8a3-45bd-97b7-d3a82b41ca2b
rules:
- apiGroups:
  - core.kubestash.com
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - storage.kubestash.com
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
- apiGroups:
  - snapshot.storage.k8s.io
  resources:
  - '*'
  verbs:
  - '*'
