apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-delete-policy: before-hook-creation
  creationTimestamp: "2025-04-28T11:27:33Z"
  labels:
    rbac.authorization.k8s.io/aggregate-to-view: "true"
  managedFields:
  - apiVersion: rbac.authorization.k8s.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:helm.sh/hook: {}
          f:helm.sh/hook-delete-policy: {}
        f:labels:
          .: {}
          f:rbac.authorization.k8s.io/aggregate-to-view: {}
      f:rules: {}
    manager: helm
    operation: Update
    time: "2025-04-28T11:27:33Z"
  name: kubedb:gitops:view
  resourceVersion: "58921"
  uid: a1db91bf-19cf-4b70-b130-1d670fdbddc6
rules:
- apiGroups:
  - gitops.kubedb.com
  resources:
  - '*'
  verbs:
  - get
  - list
  - watch
