apiVersion: addons.kubestash.com/v1alpha1
kind: Function
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"addons.kubestash.com/v1alpha1","kind":"Function","metadata":{"annotations":{},"name":"kubedump-backup"},"spec":{"args":["backup","--namespace=${namespace:=default}","--backupsession=${backupSession:=}","--enable-cache=${enableCache:=}","--scratch-dir=${scratchDir:=}","--and-label-selectors=${ANDedLabelSelector:=}","--or-label-selectors=${ORedLabelSelector:=}","--include-cluster-resources=${IncludeClusterResources:=}","--include-namespaces=${IncludeNamespaces:=}","--include-resources=${IncludeResources:=}","--exclude-resources=${ExcludeResources:=}","--exclude-namespaces=${ExcludeNamespaces:=}"],"image":"ghcr.io/anisurrahman75/kubedump:kubedump-restore_linux_amd64116"}}
    meta.helm.sh/release-name: kubestash
    meta.helm.sh/release-namespace: kubestash
  creationTimestamp: "2025-04-25T10:31:48Z"
  generation: 3
  labels:
    app.kubernetes.io/instance: kubestash
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: kubestash-catalog
    app.kubernetes.io/version: v2025.3.24
    helm.sh/chart: kubestash-catalog-v2025.3.24
  managedFields:
  - apiVersion: addons.kubestash.com/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:meta.helm.sh/release-name: {}
          f:meta.helm.sh/release-namespace: {}
        f:labels:
          .: {}
          f:app.kubernetes.io/instance: {}
          f:app.kubernetes.io/managed-by: {}
          f:app.kubernetes.io/name: {}
          f:app.kubernetes.io/version: {}
          f:helm.sh/chart: {}
      f:spec: {}
    manager: helm
    operation: Update
    time: "2025-04-25T10:31:48Z"
  - apiVersion: addons.kubestash.com/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          f:kubectl.kubernetes.io/last-applied-configuration: {}
      f:spec:
        f:args: {}
        f:image: {}
    manager: kubectl-client-side-apply
    operation: Update
    time: "2025-04-25T11:06:54Z"
  name: kubedump-backup
  resourceVersion: "4599"
  uid: d608fb35-6c5b-462c-8b80-5f61fe196412
spec:
  args:
  - backup
  - --namespace=${namespace:=default}
  - --backupsession=${backupSession:=}
  - --enable-cache=${enableCache:=}
  - --scratch-dir=${scratchDir:=}
  - --and-label-selectors=${ANDedLabelSelector:=}
  - --or-label-selectors=${ORedLabelSelector:=}
  - --include-cluster-resources=${IncludeClusterResources:=}
  - --include-namespaces=${IncludeNamespaces:=}
  - --include-resources=${IncludeResources:=}
  - --exclude-resources=${ExcludeResources:=}
  - --exclude-namespaces=${ExcludeNamespaces:=}
  image: ghcr.io/anisurrahman75/kubedump:kubedump-restore_linux_amd64116
