apiVersion: addons.kubestash.com/v1alpha1
kind: Function
metadata:
  annotations:
    meta.helm.sh/release-name: kubedb
    meta.helm.sh/release-namespace: kubedb
  creationTimestamp: "2025-04-28T11:28:31Z"
  generation: 1
  labels:
    app.kubernetes.io/instance: kubedb
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: kubedb-kubestash-catalog
    app.kubernetes.io/version: v2025.3.24
    helm.sh/chart: kubedb-kubestash-catalog-v2025.3.24
  managedFields:
  - apiVersion: addons.kubestash.com/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:meta.helm.sh/release-name: {}
          f:meta.helm.sh/release-namespace: {}
        f:labels:
          .: {}
          f:app.kubernetes.io/instance: {}
          f:app.kubernetes.io/managed-by: {}
          f:app.kubernetes.io/name: {}
          f:app.kubernetes.io/version: {}
          f:helm.sh/chart: {}
      f:spec:
        .: {}
        f:args: {}
        f:image: {}
    manager: helm
    operation: Update
    time: "2025-04-28T11:28:31Z"
  name: mssqlserver-restore
  resourceVersion: "59315"
  uid: bf5b446b-5ce4-4a3e-8228-01d38d1a88fd
spec:
  args:
  - restore
  - --namespace=${namespace:=default}
  - --restoresession=${restoreSession:=}
  - --snapshot=${snapshot:=}
  - --wait-timeout=${waitTimeout:=300}
  - --databases=${databases:=}
  - --no-recovery=${noRecovery:=false}
  image: ghcr.io/kubedb/mssqlserver-walg-plugin:v0.0.1
