apiVersion: addons.kubestash.com/v1alpha1
kind: Function
metadata:
  annotations:
    meta.helm.sh/release-name: kubedb
    meta.helm.sh/release-namespace: kubedb
  creationTimestamp: "2025-04-28T11:28:31Z"
  generation: 1
  labels:
    app.kubernetes.io/instance: kubedb
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: kubedb-kubestash-catalog
    app.kubernetes.io/version: v2025.3.24
    helm.sh/chart: kubedb-kubestash-catalog-v2025.3.24
  managedFields:
  - apiVersion: addons.kubestash.com/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:meta.helm.sh/release-name: {}
          f:meta.helm.sh/release-namespace: {}
        f:labels:
          .: {}
          f:app.kubernetes.io/instance: {}
          f:app.kubernetes.io/managed-by: {}
          f:app.kubernetes.io/name: {}
          f:app.kubernetes.io/version: {}
          f:helm.sh/chart: {}
      f:spec:
        .: {}
        f:args: {}
        f:availableVersions: {}
        f:image: {}
    manager: helm
    operation: Update
    time: "2025-04-28T11:28:31Z"
  name: mysql-physical-backup
  resourceVersion: "59317"
  uid: 29bd2156-b164-4a8c-acf4-0d6b713ee79e
spec:
  args:
  - backup
  - --namespace=${namespace:=default}
  - --backupsession=${backupSession:=}
  - --enable-cache=${enableCache:=}
  - --scratch-dir=${scratchDir:=}
  - --wait-timeout=${waitTimeout:=300}
  - --mysql-args=${args:=}
  - --data-dir=${dataDir:=}
  availableVersions:
  - 2.4.29
  - 8.0.35
  - 8.1.0
  - 8.2.0
  - 8.4.0
  image: ghcr.io/kubedb/xtrabackup-restic-plugin:v0.2.0_${DB_VERSION}
