apiVersion: addons.kubestash.com/v1alpha1
kind: Function
metadata:
  annotations:
    meta.helm.sh/release-name: kubedb
    meta.helm.sh/release-namespace: kubedb
  creationTimestamp: "2025-04-28T11:28:31Z"
  generation: 1
  labels:
    app.kubernetes.io/instance: kubedb
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: kubedb-kubestash-catalog
    app.kubernetes.io/version: v2025.3.24
    helm.sh/chart: kubedb-kubestash-catalog-v2025.3.24
  managedFields:
  - apiVersion: addons.kubestash.com/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:meta.helm.sh/release-name: {}
          f:meta.helm.sh/release-namespace: {}
        f:labels:
          .: {}
          f:app.kubernetes.io/instance: {}
          f:app.kubernetes.io/managed-by: {}
          f:app.kubernetes.io/name: {}
          f:app.kubernetes.io/version: {}
          f:helm.sh/chart: {}
      f:spec:
        .: {}
        f:args: {}
        f:availableVersions: {}
        f:image: {}
    manager: helm
    operation: Update
    time: "2025-04-28T11:28:31Z"
  name: postgres-physical-backup
  resourceVersion: "59293"
  uid: 23724540-629d-41fe-8d02-60653f54ba08
spec:
  args:
  - physical-backup
  - --namespace=${namespace:=default}
  - --backupsession=${backupSession:=}
  - --enable-cache=${enableCache:=}
  - --scratch-dir=${scratchDir:=}
  - --wait-timeout=${waitTimeout:=300}
  - --pg-args=${args:=}
  - --backup-cmd=${backupCmd:=}
  - --user=${user:=}
  availableVersions:
  - "16.1"
  - "17.2"
  image: ghcr.io/kubedb/postgres-restic-plugin:v0.16.0_${DB_VERSION}
