apiVersion: catalog.kubedb.com/v1alpha1
kind: KafkaVersion
metadata:
  annotations:
    meta.helm.sh/release-name: kubedb
    meta.helm.sh/release-namespace: kubedb
  creationTimestamp: "2025-04-28T11:28:31Z"
  generation: 1
  labels:
    app.kubernetes.io/instance: kubedb
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: kubedb-catalog
    app.kubernetes.io/version: v2025.3.24
    helm.sh/chart: kubedb-catalog-v2025.3.24
  managedFields:
  - apiVersion: catalog.kubedb.com/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:meta.helm.sh/release-name: {}
          f:meta.helm.sh/release-namespace: {}
        f:labels:
          .: {}
          f:app.kubernetes.io/instance: {}
          f:app.kubernetes.io/managed-by: {}
          f:app.kubernetes.io/name: {}
          f:app.kubernetes.io/version: {}
          f:helm.sh/chart: {}
      f:spec:
        .: {}
        f:connectCluster:
          .: {}
          f:image: {}
        f:cruiseControl:
          .: {}
          f:image: {}
        f:db:
          .: {}
          f:image: {}
        f:podSecurityPolicies:
          .: {}
          f:databasePolicyName: {}
        f:securityContext:
          .: {}
          f:runAsUser: {}
        f:ui: {}
        f:updateConstraints:
          .: {}
          f:allowlist: {}
          f:denylist: {}
        f:version: {}
    manager: helm
    operation: Update
    time: "2025-04-28T11:28:31Z"
  name: 3.9.0
  resourceVersion: "59360"
  uid: ee622bc8-b169-4d6b-bd66-bd40791d274f
spec:
  connectCluster:
    image: ghcr.io/appscode-images/kafka-connect-cluster:3.9.0
  cruiseControl:
    image: ghcr.io/appscode-images/kafka-cruise-control:3.9.0
  db:
    image: ghcr.io/appscode-images/kafka-kraft:3.9.0
  podSecurityPolicies:
    databasePolicyName: ""
  securityContext:
    runAsUser: 1001
  ui:
  - name: kafka-ui
    version: v2024.4.27
  updateConstraints:
    allowlist:
    - '>= 3.9.0'
    denylist:
    - < 3.9.0
  version: 3.9.0
