apiVersion: v1
count: 1
eventTime: null
firstTimestamp: "2025-04-28T11:29:59Z"
involvedObject:
  apiVersion: v1
  fieldPath: spec.containers{operator}
  kind: Pod
  name: kubedb-kubedb-provisioner-0
  namespace: kubedb
  resourceVersion: "59321"
  uid: 01f9b29a-b271-4d4f-9da0-5644489a6660
kind: Event
lastTimestamp: "2025-04-28T11:29:59Z"
message: Started container operator
metadata:
  creationTimestamp: "2025-04-28T11:29:59Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:count: {}
      f:firstTimestamp: {}
      f:involvedObject: {}
      f:lastTimestamp: {}
      f:message: {}
      f:reason: {}
      f:reportingComponent: {}
      f:reportingInstance: {}
      f:source:
        f:component: {}
        f:host: {}
      f:type: {}
    manager: kubelet
    operation: Update
    time: "2025-04-28T11:29:59Z"
  name: kubedb-kubedb-provisioner-0.183a780c507ea451
  namespace: kubedb
  resourceVersion: "59703"
  uid: b8fc2ec6-6860-40d9-9d3f-c9a506edfb2e
reason: Started
reportingComponent: kubelet
reportingInstance: kind-control-plane
source:
  component: kubelet
  host: kind-control-plane
type: Normal
