apiVersion: stash.appscode.com/v1alpha1
kind: Repository
metadata:
  name: gcs-repo
  namespace: demo
spec:
  backend:
    gcs:
      bucket: kubestash
      prefix: /sunny/stash-test
    storageSecretName: gcs-secret
  usagePolicy:
    allowedNamespaces:
      from: All