apiVersion: storage.kubestash.com/v1alpha1
kind: BackupStorage
metadata:
  name: s3-storage
  namespace: demo
spec:
  storage:
    provider: s3
    s3:
      bucket: aceyiywqg
      region: us-east-1
      endpoint: https://s3.us-east-1.amazonaws.com
      # secretName: aws-s3-secret
      prefix: sunny
  usagePolicy:
    allowedNamespaces:
      from: All
  default: true
  deletionPolicy: WipeOut
