apiVersion: catalog.kubedb.com/v1alpha1
kind: MariaDBVersion
metadata:
  annotations:
    meta.helm.sh/release-name: kubedb
    meta.helm.sh/release-namespace: kubedb
  creationTimestamp: "2025-04-28T11:28:31Z"
  generation: 1
  labels:
    app.kubernetes.io/instance: kubedb
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: kubedb-catalog
    app.kubernetes.io/version: v2025.3.24
    helm.sh/chart: kubedb-catalog-v2025.3.24
  managedFields:
  - apiVersion: catalog.kubedb.com/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:meta.helm.sh/release-name: {}
          f:meta.helm.sh/release-namespace: {}
        f:labels:
          .: {}
          f:app.kubernetes.io/instance: {}
          f:app.kubernetes.io/managed-by: {}
          f:app.kubernetes.io/name: {}
          f:app.kubernetes.io/version: {}
          f:helm.sh/chart: {}
      f:spec:
        .: {}
        f:archiver:
          .: {}
          f:addon:
            .: {}
            f:name: {}
            f:tasks:
              .: {}
              f:fullBackup:
                .: {}
                f:name: {}
              f:fullBackupRestore:
                .: {}
                f:name: {}
              f:manifestBackup:
                .: {}
                f:name: {}
              f:manifestRestore:
                .: {}
                f:name: {}
              f:volumeSnapshot:
                .: {}
                f:name: {}
          f:walg:
            .: {}
            f:image: {}
        f:coordinator:
          .: {}
          f:image: {}
        f:db:
          .: {}
          f:image: {}
        f:exporter:
          .: {}
          f:image: {}
        f:initContainer:
          .: {}
          f:image: {}
        f:maxscale:
          .: {}
          f:image: {}
          f:securityContext:
            .: {}
            f:runAsUser: {}
        f:podSecurityPolicies:
          .: {}
          f:databasePolicyName: {}
        f:securityContext:
          .: {}
          f:runAsUser: {}
        f:stash:
          .: {}
          f:addon:
            .: {}
            f:backupTask:
              .: {}
              f:name: {}
            f:restoreTask:
              .: {}
              f:name: {}
        f:ui: {}
        f:updateConstraints:
          .: {}
          f:allowlist: {}
        f:version: {}
    manager: helm
    operation: Update
    time: "2025-04-28T11:28:31Z"
  name: 11.0.4
  resourceVersion: "59374"
  uid: 5b43586d-98f4-4f21-b350-cf7112647737
spec:
  archiver:
    addon:
      name: mariadb-addon
      tasks:
        fullBackup:
          name: logical-backup
        fullBackupRestore:
          name: logical-backup-restore
        manifestBackup:
          name: manifest-backup
        manifestRestore:
          name: manifest-restore
        volumeSnapshot:
          name: volume-snapshot
    walg:
      image: ghcr.io/kubedb/mariadb-archiver:v0.13.0_11.0.4-jammy
  coordinator:
    image: ghcr.io/kubedb/mariadb-coordinator:v0.33.0
  db:
    image: ghcr.io/appscode-images/mariadb:11.0.4-jammy
  exporter:
    image: prom/mysqld-exporter:v0.13.0
  initContainer:
    image: ghcr.io/kubedb/mariadb-init:0.5.3
  maxscale:
    image: mariadb/maxscale:24.02.4
    securityContext:
      runAsUser: 997
  podSecurityPolicies:
    databasePolicyName: ""
  securityContext:
    runAsUser: 999
  stash:
    addon:
      backupTask:
        name: mariadb-backup-10.5.8
      restoreTask:
        name: mariadb-restore-10.5.8
  ui:
  - name: phpmyadmin
    version: v2024.4.27
  updateConstraints:
    allowlist:
    - '>= 11.0.4, <= 11.6.2'
  version: 11.0.4
