apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
    meta.helm.sh/release-name: kubedb
    meta.helm.sh/release-namespace: kubedb
  creationTimestamp: "2025-04-28T11:28:31Z"
  labels:
    app.kubernetes.io/instance: kubedb
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: sidekick
    app.kubernetes.io/version: v0.0.11
    helm.sh/chart: sidekick-v2025.3.14
  managedFields:
  - apiVersion: rbac.authorization.k8s.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:meta.helm.sh/release-name: {}
          f:meta.helm.sh/release-namespace: {}
        f:labels:
          .: {}
          f:app.kubernetes.io/instance: {}
          f:app.kubernetes.io/managed-by: {}
          f:app.kubernetes.io/name: {}
          f:app.kubernetes.io/version: {}
          f:helm.sh/chart: {}
      f:roleRef: {}
      f:subjects: {}
    manager: helm
    operation: Update
    time: "2025-04-28T11:28:31Z"
  name: kubedb-sidekick
  resourceVersion: "59171"
  uid: c45d57cb-b563-4270-afb3-a880c33648b8
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kubedb-sidekick
subjects:
- kind: ServiceAccount
  name: kubedb-sidekick
  namespace: kubedb
