apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  creationTimestamp: "2025-04-25T10:16:39Z"
  managedFields:
  - apiVersion: rbac.authorization.k8s.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:roleRef: {}
      f:subjects: {}
    manager: kubeadm
    operation: Update
    time: "2025-04-25T10:16:39Z"
  name: kubeadm:node-autoapprove-certificate-rotation
  resourceVersion: "216"
  uid: cd2c3d55-4ad5-41fd-8180-9b6cc9044e91
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:certificates.k8s.io:certificatesigningrequests:selfnodeclient
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: system:nodes
