apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
    meta.helm.sh/release-name: kubestash
    meta.helm.sh/release-namespace: kubestash
  creationTimestamp: "2025-04-25T10:31:48Z"
  labels:
    app.kubernetes.io/managed-by: Helm
  managedFields:
  - apiVersion: rbac.authorization.k8s.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:meta.helm.sh/release-name: {}
          f:meta.helm.sh/release-namespace: {}
        f:labels:
          .: {}
          f:app.kubernetes.io/managed-by: {}
      f:roleRef: {}
      f:subjects: {}
    manager: helm
    operation: Update
    time: "2025-04-25T10:31:48Z"
  name: kubestash-kubestash-operator-auth-delegator
  resourceVersion: "1688"
  uid: 0f5761d5-d3ee-41df-8187-d0e9f6e8c309
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
- kind: ServiceAccount
  name: kubestash-kubestash-operator
  namespace: kubestash
