apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  creationTimestamp: "2025-04-25T10:16:40Z"
  managedFields:
  - apiVersion: rbac.authorization.k8s.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:roleRef: {}
      f:subjects: {}
    manager: kubeadm
    operation: Update
    time: "2025-04-25T10:16:40Z"
  name: kubeadm:node-proxier
  resourceVersion: "238"
  uid: 4b23ee38-56ed-4b24-893d-bcb50675b6f4
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:node-proxier
subjects:
- kind: ServiceAccount
  name: kube-proxy
  namespace: kube-system
