apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
  creationTimestamp: "2025-04-25T10:16:39Z"
  labels:
    kubernetes.io/bootstrapping: rbac-defaults
  managedFields:
  - apiVersion: rbac.authorization.k8s.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:rbac.authorization.kubernetes.io/autoupdate: {}
        f:labels:
          .: {}
          f:kubernetes.io/bootstrapping: {}
      f:roleRef: {}
      f:subjects: {}
    manager: kube-apiserver
    operation: Update
    time: "2025-04-25T10:16:39Z"
  name: system:controller:legacy-service-account-token-cleaner
  resourceVersion: "179"
  uid: 7a519325-0732-4239-a57a-b8cf3b277eb0
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:controller:legacy-service-account-token-cleaner
subjects:
- kind: ServiceAccount
  name: legacy-service-account-token-cleaner
  namespace: kube-system
