apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
  creationTimestamp: "2025-04-25T10:16:39Z"
  labels:
    kubernetes.io/bootstrapping: rbac-defaults
  managedFields:
  - apiVersion: rbac.authorization.k8s.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:rbac.authorization.kubernetes.io/autoupdate: {}
        f:labels:
          .: {}
          f:kubernetes.io/bootstrapping: {}
      f:roleRef: {}
      f:subjects: {}
    manager: kube-apiserver
    operation: Update
    time: "2025-04-25T10:16:39Z"
  name: system:controller:pvc-protection-controller
  resourceVersion: "174"
  uid: a5969524-630f-49c2-b2e0-d7c0e7f4b5e5
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:controller:pvc-protection-controller
subjects:
- kind: ServiceAccount
  name: pvc-protection-controller
  namespace: kube-system
