addressType: IPv4
apiVersion: discovery.k8s.io/v1
endpoints:
- addresses:
  - 10.244.0.16
  conditions:
    ready: true
    serving: true
    terminating: false
  nodeName: kind-control-plane
  targetRef:
    kind: Pod
    name: kubedb-kubedb-webhook-server-5954c556dd-dc2m5
    namespace: kubedb
    uid: be643667-f42a-4f36-8779-352512231b02
kind: EndpointSlice
metadata:
  annotations:
    endpoints.kubernetes.io/last-change-trigger-time: "2025-04-28T11:29:12Z"
  creationTimestamp: "2025-04-28T11:28:31Z"
  generateName: kubedb-kubedb-webhook-server-
  generation: 3
  labels:
    app.kubernetes.io/instance: kubedb
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: kubedb-webhook-server
    app.kubernetes.io/version: v0.29.1
    endpointslice.kubernetes.io/managed-by: endpointslice-controller.k8s.io
    helm.sh/chart: kubedb-webhook-server-v0.29.0
    kubernetes.io/service-name: kubedb-kubedb-webhook-server
  managedFields:
  - apiVersion: discovery.k8s.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:addressType: {}
      f:endpoints: {}
      f:metadata:
        f:annotations:
          .: {}
          f:endpoints.kubernetes.io/last-change-trigger-time: {}
        f:generateName: {}
        f:labels:
          .: {}
          f:app.kubernetes.io/instance: {}
          f:app.kubernetes.io/managed-by: {}
          f:app.kubernetes.io/name: {}
          f:app.kubernetes.io/version: {}
          f:endpointslice.kubernetes.io/managed-by: {}
          f:helm.sh/chart: {}
          f:kubernetes.io/service-name: {}
        f:ownerReferences:
          .: {}
          k:{"uid":"fc07fe4c-327d-466c-8b38-7a8b0c007305"}: {}
      f:ports: {}
    manager: kube-controller-manager
    operation: Update
    time: "2025-04-28T11:29:12Z"
  name: kubedb-kubedb-webhook-server-hszg9
  namespace: kubedb
  ownerReferences:
  - apiVersion: v1
    blockOwnerDeletion: true
    controller: true
    kind: Service
    name: kubedb-kubedb-webhook-server
    uid: fc07fe4c-327d-466c-8b38-7a8b0c007305
  resourceVersion: "59616"
  uid: 33bba8f8-b07b-4e0f-b787-c438dd48c36f
ports:
- name: metrics
  port: 8443
  protocol: TCP
- name: https
  port: 9443
  protocol: TCP
