addressType: IPv4
apiVersion: discovery.k8s.io/v1
endpoints:
- addresses:
  - 10.244.0.19
  conditions:
    ready: true
    serving: true
    terminating: false
  nodeName: kind-control-plane
  targetRef:
    kind: Pod
    name: kubedb-sidekick-64557ff5dd-g2xpt
    namespace: kubedb
    uid: 12eb5a56-97d4-446e-896d-52b21d229995
kind: EndpointSlice
metadata:
  annotations:
    endpoints.kubernetes.io/last-change-trigger-time: "2025-04-28T11:28:58Z"
  creationTimestamp: "2025-04-28T11:28:31Z"
  generateName: kubedb-sidekick-
  generation: 2
  labels:
    app.kubernetes.io/instance: kubedb
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: sidekick
    app.kubernetes.io/version: v0.0.11
    endpointslice.kubernetes.io/managed-by: endpointslice-controller.k8s.io
    helm.sh/chart: sidekick-v2025.3.14
    kubernetes.io/service-name: kubedb-sidekick
  managedFields:
  - apiVersion: discovery.k8s.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:addressType: {}
      f:endpoints: {}
      f:metadata:
        f:annotations:
          .: {}
          f:endpoints.kubernetes.io/last-change-trigger-time: {}
        f:generateName: {}
        f:labels:
          .: {}
          f:app.kubernetes.io/instance: {}
          f:app.kubernetes.io/managed-by: {}
          f:app.kubernetes.io/name: {}
          f:app.kubernetes.io/version: {}
          f:endpointslice.kubernetes.io/managed-by: {}
          f:helm.sh/chart: {}
          f:kubernetes.io/service-name: {}
        f:ownerReferences:
          .: {}
          k:{"uid":"dc06b7d1-9341-4b0b-b47e-4af2c1f1658c"}: {}
      f:ports: {}
    manager: kube-controller-manager
    operation: Update
    time: "2025-04-28T11:28:58Z"
  name: kubedb-sidekick-bgr6k
  namespace: kubedb
  ownerReferences:
  - apiVersion: v1
    blockOwnerDeletion: true
    controller: true
    kind: Service
    name: kubedb-sidekick
    uid: dc06b7d1-9341-4b0b-b47e-4af2c1f1658c
  resourceVersion: "59587"
  uid: b1732d6d-d302-4f38-8c2a-351fb044a705
ports:
- name: metrics
  port: 8443
  protocol: TCP
- name: https
  port: 9443
  protocol: TCP
