apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: "2025-04-25T10:35:31Z"
  labels:
    kubernetes.io/metadata.name: demo
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:labels:
          .: {}
          f:kubernetes.io/metadata.name: {}
    manager: kubectl-create
    operation: Update
    time: "2025-04-25T10:35:31Z"
  name: demo
  resourceVersion: "2051"
  uid: 63d51f9b-b644-42c7-8d5a-31e29594e2d3
spec:
  finalizers:
  - kubernetes
status:
  phase: Active
